<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cerbos/policy/v1/policy.proto

namespace Cerbos\Policy\V1\PBMatch;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>cerbos.policy.v1.Match.ExprList</code>
 */
class ExprList extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .cerbos.policy.v1.Match of = 1 [json_name = "of"];</code>
     */
    private $of;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Cerbos\Policy\V1\PBMatch[] $of
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Cerbos\Policy\V1\Policy::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .cerbos.policy.v1.Match of = 1 [json_name = "of"];</code>
     * @return RepeatedField<\Cerbos\Policy\V1\PBMatch>
     */
    public function getOf()
    {
        return $this->of;
    }

    /**
     * Generated from protobuf field <code>repeated .cerbos.policy.v1.Match of = 1 [json_name = "of"];</code>
     * @param \Cerbos\Policy\V1\PBMatch[] $var
     * @return $this
     */
    public function setOf($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Cerbos\Policy\V1\PBMatch::class);
        $this->of = $arr;

        return $this;
    }

}

