<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cerbos/cloud/bundle/v2/bundle.proto

namespace Cerbos\Cloud\Bundle\V2;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * BundleInfo holds information about a bundle and its download URLs.
 *
 * Generated from protobuf message <code>cerbos.cloud.bundle.v2.BundleInfo</code>
 */
class BundleInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.cerbos.cloud.bundle.v2.Source source = 1 [json_name = "source"];</code>
     */
    protected $source = null;
    /**
     * Generated from protobuf field <code>bytes input_hash = 2 [json_name = "inputHash"];</code>
     */
    protected $input_hash = '';
    /**
     * Generated from protobuf field <code>bytes output_hash = 3 [json_name = "outputHash"];</code>
     */
    protected $output_hash = '';
    /**
     * Generated from protobuf field <code>bytes encryption_key = 4 [json_name = "encryptionKey"];</code>
     */
    protected $encryption_key = '';
    /**
     * Generated from protobuf field <code>repeated .cerbos.cloud.bundle.v2.BundleInfo.Segment segments = 5 [json_name = "segments"];</code>
     */
    private $segments;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Cerbos\Cloud\Bundle\V2\Source $source
     *     @type string $input_hash
     *     @type string $output_hash
     *     @type string $encryption_key
     *     @type \Cerbos\Cloud\Bundle\V2\BundleInfo\Segment[] $segments
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Cerbos\Cloud\Bundle\V2\Bundle::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.cerbos.cloud.bundle.v2.Source source = 1 [json_name = "source"];</code>
     * @return \Cerbos\Cloud\Bundle\V2\Source|null
     */
    public function getSource()
    {
        return $this->source;
    }

    public function hasSource()
    {
        return isset($this->source);
    }

    public function clearSource()
    {
        unset($this->source);
    }

    /**
     * Generated from protobuf field <code>.cerbos.cloud.bundle.v2.Source source = 1 [json_name = "source"];</code>
     * @param \Cerbos\Cloud\Bundle\V2\Source $var
     * @return $this
     */
    public function setSource($var)
    {
        GPBUtil::checkMessage($var, \Cerbos\Cloud\Bundle\V2\Source::class);
        $this->source = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes input_hash = 2 [json_name = "inputHash"];</code>
     * @return string
     */
    public function getInputHash()
    {
        return $this->input_hash;
    }

    /**
     * Generated from protobuf field <code>bytes input_hash = 2 [json_name = "inputHash"];</code>
     * @param string $var
     * @return $this
     */
    public function setInputHash($var)
    {
        GPBUtil::checkString($var, False);
        $this->input_hash = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes output_hash = 3 [json_name = "outputHash"];</code>
     * @return string
     */
    public function getOutputHash()
    {
        return $this->output_hash;
    }

    /**
     * Generated from protobuf field <code>bytes output_hash = 3 [json_name = "outputHash"];</code>
     * @param string $var
     * @return $this
     */
    public function setOutputHash($var)
    {
        GPBUtil::checkString($var, False);
        $this->output_hash = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes encryption_key = 4 [json_name = "encryptionKey"];</code>
     * @return string
     */
    public function getEncryptionKey()
    {
        return $this->encryption_key;
    }

    /**
     * Generated from protobuf field <code>bytes encryption_key = 4 [json_name = "encryptionKey"];</code>
     * @param string $var
     * @return $this
     */
    public function setEncryptionKey($var)
    {
        GPBUtil::checkString($var, False);
        $this->encryption_key = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .cerbos.cloud.bundle.v2.BundleInfo.Segment segments = 5 [json_name = "segments"];</code>
     * @return RepeatedField<\Cerbos\Cloud\Bundle\V2\BundleInfo\Segment>
     */
    public function getSegments()
    {
        return $this->segments;
    }

    /**
     * Generated from protobuf field <code>repeated .cerbos.cloud.bundle.v2.BundleInfo.Segment segments = 5 [json_name = "segments"];</code>
     * @param \Cerbos\Cloud\Bundle\V2\BundleInfo\Segment[] $var
     * @return $this
     */
    public function setSegments($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Cerbos\Cloud\Bundle\V2\BundleInfo\Segment::class);
        $this->segments = $arr;

        return $this;
    }

}

