<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cerbos/cloud/bundle/v2/bundle.proto

namespace Cerbos\Cloud\Bundle\V2;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>cerbos.cloud.bundle.v2.WatchBundleRequest</code>
 */
class WatchBundleRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.cerbos.cloud.pdp.v1.Identifier pdp_id = 1 [json_name = "pdpId"];</code>
     */
    protected $pdp_id = null;
    protected $msg;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Cerbos\Cloud\Pdp\V1\Identifier $pdp_id
     *     @type \Cerbos\Cloud\Bundle\V2\WatchBundleRequest\Start $start
     *     @type \Cerbos\Cloud\Bundle\V2\WatchBundleRequest\Heartbeat $heartbeat
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Cerbos\Cloud\Bundle\V2\Bundle::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.cerbos.cloud.pdp.v1.Identifier pdp_id = 1 [json_name = "pdpId"];</code>
     * @return \Cerbos\Cloud\Pdp\V1\Identifier|null
     */
    public function getPdpId()
    {
        return $this->pdp_id;
    }

    public function hasPdpId()
    {
        return isset($this->pdp_id);
    }

    public function clearPdpId()
    {
        unset($this->pdp_id);
    }

    /**
     * Generated from protobuf field <code>.cerbos.cloud.pdp.v1.Identifier pdp_id = 1 [json_name = "pdpId"];</code>
     * @param \Cerbos\Cloud\Pdp\V1\Identifier $var
     * @return $this
     */
    public function setPdpId($var)
    {
        GPBUtil::checkMessage($var, \Cerbos\Cloud\Pdp\V1\Identifier::class);
        $this->pdp_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.cerbos.cloud.bundle.v2.WatchBundleRequest.Start start = 2 [json_name = "start"];</code>
     * @return \Cerbos\Cloud\Bundle\V2\WatchBundleRequest\Start|null
     */
    public function getStart()
    {
        return $this->readOneof(2);
    }

    public function hasStart()
    {
        return $this->hasOneof(2);
    }

    /**
     * Generated from protobuf field <code>.cerbos.cloud.bundle.v2.WatchBundleRequest.Start start = 2 [json_name = "start"];</code>
     * @param \Cerbos\Cloud\Bundle\V2\WatchBundleRequest\Start $var
     * @return $this
     */
    public function setStart($var)
    {
        GPBUtil::checkMessage($var, \Cerbos\Cloud\Bundle\V2\WatchBundleRequest\Start::class);
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.cerbos.cloud.bundle.v2.WatchBundleRequest.Heartbeat heartbeat = 3 [json_name = "heartbeat"];</code>
     * @return \Cerbos\Cloud\Bundle\V2\WatchBundleRequest\Heartbeat|null
     */
    public function getHeartbeat()
    {
        return $this->readOneof(3);
    }

    public function hasHeartbeat()
    {
        return $this->hasOneof(3);
    }

    /**
     * Generated from protobuf field <code>.cerbos.cloud.bundle.v2.WatchBundleRequest.Heartbeat heartbeat = 3 [json_name = "heartbeat"];</code>
     * @param \Cerbos\Cloud\Bundle\V2\WatchBundleRequest\Heartbeat $var
     * @return $this
     */
    public function setHeartbeat($var)
    {
        GPBUtil::checkMessage($var, \Cerbos\Cloud\Bundle\V2\WatchBundleRequest\Heartbeat::class);
        $this->writeOneof(3, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getMsg()
    {
        return $this->whichOneof("msg");
    }

}

