<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cerbos/cloud/bundle/v1/bundle.proto

namespace Cerbos\Cloud\Bundle\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * BundleInfo holds information about a bundle and its download URLs.
 *
 * Generated from protobuf message <code>cerbos.cloud.bundle.v1.BundleInfo</code>
 */
class BundleInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string label = 1 [json_name = "label"];</code>
     */
    protected $label = '';
    /**
     * Generated from protobuf field <code>bytes bundle_hash = 2 [json_name = "bundleHash"];</code>
     */
    protected $bundle_hash = '';
    /**
     * Generated from protobuf field <code>repeated .cerbos.cloud.bundle.v1.BundleInfo.Segment segments = 3 [json_name = "segments"];</code>
     */
    private $segments;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $label
     *     @type string $bundle_hash
     *     @type \Cerbos\Cloud\Bundle\V1\BundleInfo\Segment[] $segments
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Cerbos\Cloud\Bundle\V1\Bundle::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string label = 1 [json_name = "label"];</code>
     * @return string
     */
    public function getLabel()
    {
        return $this->label;
    }

    /**
     * Generated from protobuf field <code>string label = 1 [json_name = "label"];</code>
     * @param string $var
     * @return $this
     */
    public function setLabel($var)
    {
        GPBUtil::checkString($var, True);
        $this->label = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes bundle_hash = 2 [json_name = "bundleHash"];</code>
     * @return string
     */
    public function getBundleHash()
    {
        return $this->bundle_hash;
    }

    /**
     * Generated from protobuf field <code>bytes bundle_hash = 2 [json_name = "bundleHash"];</code>
     * @param string $var
     * @return $this
     */
    public function setBundleHash($var)
    {
        GPBUtil::checkString($var, False);
        $this->bundle_hash = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .cerbos.cloud.bundle.v1.BundleInfo.Segment segments = 3 [json_name = "segments"];</code>
     * @return RepeatedField<\Cerbos\Cloud\Bundle\V1\BundleInfo\Segment>
     */
    public function getSegments()
    {
        return $this->segments;
    }

    /**
     * Generated from protobuf field <code>repeated .cerbos.cloud.bundle.v1.BundleInfo.Segment segments = 3 [json_name = "segments"];</code>
     * @param \Cerbos\Cloud\Bundle\V1\BundleInfo\Segment[] $var
     * @return $this
     */
    public function setSegments($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Cerbos\Cloud\Bundle\V1\BundleInfo\Segment::class);
        $this->segments = $arr;

        return $this;
    }

}

