<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cerbos/cloud/bundle/v1/bundle.proto

namespace Cerbos\Cloud\Bundle\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>cerbos.cloud.bundle.v1.GetBundleRequest</code>
 */
class GetBundleRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.cerbos.cloud.pdp.v1.Identifier pdp_id = 1 [json_name = "pdpId"];</code>
     */
    protected $pdp_id = null;
    /**
     * Generated from protobuf field <code>string bundle_label = 2 [json_name = "bundleLabel"];</code>
     */
    protected $bundle_label = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Cerbos\Cloud\Pdp\V1\Identifier $pdp_id
     *     @type string $bundle_label
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Cerbos\Cloud\Bundle\V1\Bundle::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.cerbos.cloud.pdp.v1.Identifier pdp_id = 1 [json_name = "pdpId"];</code>
     * @return \Cerbos\Cloud\Pdp\V1\Identifier|null
     */
    public function getPdpId()
    {
        return $this->pdp_id;
    }

    public function hasPdpId()
    {
        return isset($this->pdp_id);
    }

    public function clearPdpId()
    {
        unset($this->pdp_id);
    }

    /**
     * Generated from protobuf field <code>.cerbos.cloud.pdp.v1.Identifier pdp_id = 1 [json_name = "pdpId"];</code>
     * @param \Cerbos\Cloud\Pdp\V1\Identifier $var
     * @return $this
     */
    public function setPdpId($var)
    {
        GPBUtil::checkMessage($var, \Cerbos\Cloud\Pdp\V1\Identifier::class);
        $this->pdp_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string bundle_label = 2 [json_name = "bundleLabel"];</code>
     * @return string
     */
    public function getBundleLabel()
    {
        return $this->bundle_label;
    }

    /**
     * Generated from protobuf field <code>string bundle_label = 2 [json_name = "bundleLabel"];</code>
     * @param string $var
     * @return $this
     */
    public function setBundleLabel($var)
    {
        GPBUtil::checkString($var, True);
        $this->bundle_label = $var;

        return $this;
    }

}

