<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cerbos/cloud/bundle/v1/bundle.proto

namespace Cerbos\Cloud\Bundle\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>cerbos.cloud.bundle.v1.WatchBundleRequest</code>
 */
class WatchBundleRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.cerbos.cloud.pdp.v1.Identifier pdp_id = 1 [json_name = "pdpId"];</code>
     */
    protected $pdp_id = null;
    protected $msg;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Cerbos\Cloud\Pdp\V1\Identifier $pdp_id
     *     @type \Cerbos\Cloud\Bundle\V1\WatchBundleRequest\WatchLabel $watch_label
     *     @type \Cerbos\Cloud\Bundle\V1\WatchBundleRequest\Heartbeat $heartbeat
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Cerbos\Cloud\Bundle\V1\Bundle::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.cerbos.cloud.pdp.v1.Identifier pdp_id = 1 [json_name = "pdpId"];</code>
     * @return \Cerbos\Cloud\Pdp\V1\Identifier|null
     */
    public function getPdpId()
    {
        return $this->pdp_id;
    }

    public function hasPdpId()
    {
        return isset($this->pdp_id);
    }

    public function clearPdpId()
    {
        unset($this->pdp_id);
    }

    /**
     * Generated from protobuf field <code>.cerbos.cloud.pdp.v1.Identifier pdp_id = 1 [json_name = "pdpId"];</code>
     * @param \Cerbos\Cloud\Pdp\V1\Identifier $var
     * @return $this
     */
    public function setPdpId($var)
    {
        GPBUtil::checkMessage($var, \Cerbos\Cloud\Pdp\V1\Identifier::class);
        $this->pdp_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.cerbos.cloud.bundle.v1.WatchBundleRequest.WatchLabel watch_label = 2 [json_name = "watchLabel"];</code>
     * @return \Cerbos\Cloud\Bundle\V1\WatchBundleRequest\WatchLabel|null
     */
    public function getWatchLabel()
    {
        return $this->readOneof(2);
    }

    public function hasWatchLabel()
    {
        return $this->hasOneof(2);
    }

    /**
     * Generated from protobuf field <code>.cerbos.cloud.bundle.v1.WatchBundleRequest.WatchLabel watch_label = 2 [json_name = "watchLabel"];</code>
     * @param \Cerbos\Cloud\Bundle\V1\WatchBundleRequest\WatchLabel $var
     * @return $this
     */
    public function setWatchLabel($var)
    {
        GPBUtil::checkMessage($var, \Cerbos\Cloud\Bundle\V1\WatchBundleRequest\WatchLabel::class);
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.cerbos.cloud.bundle.v1.WatchBundleRequest.Heartbeat heartbeat = 3 [json_name = "heartbeat"];</code>
     * @return \Cerbos\Cloud\Bundle\V1\WatchBundleRequest\Heartbeat|null
     */
    public function getHeartbeat()
    {
        return $this->readOneof(3);
    }

    public function hasHeartbeat()
    {
        return $this->hasOneof(3);
    }

    /**
     * Generated from protobuf field <code>.cerbos.cloud.bundle.v1.WatchBundleRequest.Heartbeat heartbeat = 3 [json_name = "heartbeat"];</code>
     * @param \Cerbos\Cloud\Bundle\V1\WatchBundleRequest\Heartbeat $var
     * @return $this
     */
    public function setHeartbeat($var)
    {
        GPBUtil::checkMessage($var, \Cerbos\Cloud\Bundle\V1\WatchBundleRequest\Heartbeat::class);
        $this->writeOneof(3, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getMsg()
    {
        return $this->whichOneof("msg");
    }

}

