<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cerbos/policy/v1/policy.proto

namespace Cerbos\Policy\V1\TestFixture;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>cerbos.policy.v1.TestFixture.Principals</code>
 */
class Principals extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>map<string, .cerbos.engine.v1.Principal> principals = 1 [json_name = "principals"];</code>
     */
    private $principals;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array|\Google\Protobuf\Internal\MapField $principals
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Cerbos\Policy\V1\Policy::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>map<string, .cerbos.engine.v1.Principal> principals = 1 [json_name = "principals"];</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getPrincipals()
    {
        return $this->principals;
    }

    /**
     * Generated from protobuf field <code>map<string, .cerbos.engine.v1.Principal> principals = 1 [json_name = "principals"];</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setPrincipals($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::MESSAGE, \Cerbos\Engine\V1\Principal::class);
        $this->principals = $arr;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Principals::class, \Cerbos\Policy\V1\TestFixture_Principals::class);

