<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cerbos/cloud/logs/v1/logs.proto

namespace GPBMetadata\Cerbos\Cloud\Logs\V1;

class Logs
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Cerbos\Audit\V1\Audit::initOnce();
        \GPBMetadata\Cerbos\Cloud\Pdp\V1\Pdp::initOnce();
        \GPBMetadata\Google\Api\Visibility::initOnce();
        \GPBMetadata\Google\Protobuf\Duration::initOnce();
        \GPBMetadata\Google\Protobuf\GPBEmpty::initOnce();
        \GPBMetadata\Google\Protobuf\Timestamp::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\xA5\x0A\x0A\x1Fcerbos/cloud/logs/v1/logs.proto\x12\x14cerbos.cloud.logs.v1\x1A\x1Dcerbos/cloud/pdp/v1/pdp.proto\x1A\x1Bgoogle/api/visibility.proto\x1A\x1Egoogle/protobuf/duration.proto\x1A\x1Bgoogle/protobuf/empty.proto\x1A\x1Fgoogle/protobuf/timestamp.proto\"\xEF\x03\x0A\x0BIngestBatch\x12\x0E\x0A\x02id\x18\x01 \x01(\x09R\x02id\x12A\x0A\x07entries\x18\x02 \x03(\x0B2'.cerbos.cloud.logs.v1.IngestBatch.EntryR\x07entries\x1A\xAB\x02\x0A\x05Entry\x12?\x0A\x04kind\x18\x01 \x01(\x0E2+.cerbos.cloud.logs.v1.IngestBatch.EntryKindR\x04kind\x128\x0A\x09timestamp\x18\x02 \x01(\x0B2\x1A.google.protobuf.TimestampR\x09timestamp\x12K\x0A\x10access_log_entry\x18\x03 \x01(\x0B2\x1F.cerbos.audit.v1.AccessLogEntryH\x00R\x0EaccessLogEntry\x12Q\x0A\x12decision_log_entry\x18\x04 \x01(\x0B2!.cerbos.audit.v1.DecisionLogEntryH\x00R\x10decisionLogEntryB\x07\x0A\x05entry\"_\x0A\x09EntryKind\x12\x1A\x0A\x16ENTRY_KIND_UNSPECIFIED\x10\x00\x12\x19\x0A\x15ENTRY_KIND_ACCESS_LOG\x10\x01\x12\x1B\x0A\x17ENTRY_KIND_DECISION_LOG\x10\x02\"\x80\x01\x0A\x0DIngestRequest\x126\x0A\x06pdp_id\x18\x01 \x01(\x0B2\x1F.cerbos.cloud.pdp.v1.IdentifierR\x05pdpId\x127\x0A\x05batch\x18\x02 \x01(\x0B2!.cerbos.cloud.logs.v1.IngestBatchR\x05batch\"\xDA\x01\x0A\x0EIngestResponse\x122\x0A\x07success\x18\x01 \x01(\x0B2\x16.google.protobuf.EmptyH\x00R\x07success\x12H\x0A\x07backoff\x18\x02 \x01(\x0B2,.cerbos.cloud.logs.v1.IngestResponse.BackoffH\x00R\x07backoff\x1A@\x0A\x07Backoff\x125\x0A\x08duration\x18\x01 \x01(\x0B2\x19.google.protobuf.DurationR\x08durationB\x08\x0A\x06status2~\x0A\x11CerbosLogsService\x12S\x0A\x06Ingest\x12#.cerbos.cloud.logs.v1.IngestRequest\x1A\$.cerbos.cloud.logs.v1.IngestResponse\x1A\x14\xFA\xD2\xE4\x93\x02\x0E\x12\x0CEXPERIMENTALBx\x0A\x1Cdev.cerbos.api.cloud.v1.logsZ=github.com/cerbos/cloud-api/genpb/cerbos/cloud/logs/v1;logsv1\xAA\x02\x18Cerbos.Api.Cloud.V1.Logsb\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

