<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cerbos/request/v1/request.proto

namespace Cerbos\Request\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>cerbos.request.v1.AddOrUpdatePolicyRequest</code>
 */
class AddOrUpdatePolicyRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .cerbos.policy.v1.Policy policies = 1 [json_name = "policies", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     */
    private $policies;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Cerbos\Policy\V1\Policy[] $policies
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Cerbos\Request\V1\Request::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .cerbos.policy.v1.Policy policies = 1 [json_name = "policies", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @return RepeatedField<\Cerbos\Policy\V1\Policy>
     */
    public function getPolicies()
    {
        return $this->policies;
    }

    /**
     * Generated from protobuf field <code>repeated .cerbos.policy.v1.Policy policies = 1 [json_name = "policies", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @param \Cerbos\Policy\V1\Policy[] $var
     * @return $this
     */
    public function setPolicies($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Cerbos\Policy\V1\Policy::class);
        $this->policies = $arr;

        return $this;
    }

}

