<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cerbos/request/v1/request.proto

namespace Cerbos\Request\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>cerbos.request.v1.ListPoliciesRequest</code>
 */
class ListPoliciesRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bool include_disabled = 1 [json_name = "includeDisabled", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     */
    protected $include_disabled = false;
    /**
     * Generated from protobuf field <code>string name_regexp = 2 [json_name = "nameRegexp", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     */
    protected $name_regexp = '';
    /**
     * Generated from protobuf field <code>string scope_regexp = 3 [json_name = "scopeRegexp", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     */
    protected $scope_regexp = '';
    /**
     * Generated from protobuf field <code>string version_regexp = 4 [json_name = "versionRegexp", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     */
    protected $version_regexp = '';
    /**
     * Generated from protobuf field <code>repeated string policy_id = 5 [json_name = "policyId", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     */
    private $policy_id;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $include_disabled
     *     @type string $name_regexp
     *     @type string $scope_regexp
     *     @type string $version_regexp
     *     @type string[] $policy_id
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Cerbos\Request\V1\Request::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bool include_disabled = 1 [json_name = "includeDisabled", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @return bool
     */
    public function getIncludeDisabled()
    {
        return $this->include_disabled;
    }

    /**
     * Generated from protobuf field <code>bool include_disabled = 1 [json_name = "includeDisabled", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @param bool $var
     * @return $this
     */
    public function setIncludeDisabled($var)
    {
        GPBUtil::checkBool($var);
        $this->include_disabled = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string name_regexp = 2 [json_name = "nameRegexp", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @return string
     */
    public function getNameRegexp()
    {
        return $this->name_regexp;
    }

    /**
     * Generated from protobuf field <code>string name_regexp = 2 [json_name = "nameRegexp", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @param string $var
     * @return $this
     */
    public function setNameRegexp($var)
    {
        GPBUtil::checkString($var, True);
        $this->name_regexp = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string scope_regexp = 3 [json_name = "scopeRegexp", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @return string
     */
    public function getScopeRegexp()
    {
        return $this->scope_regexp;
    }

    /**
     * Generated from protobuf field <code>string scope_regexp = 3 [json_name = "scopeRegexp", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @param string $var
     * @return $this
     */
    public function setScopeRegexp($var)
    {
        GPBUtil::checkString($var, True);
        $this->scope_regexp = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string version_regexp = 4 [json_name = "versionRegexp", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @return string
     */
    public function getVersionRegexp()
    {
        return $this->version_regexp;
    }

    /**
     * Generated from protobuf field <code>string version_regexp = 4 [json_name = "versionRegexp", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @param string $var
     * @return $this
     */
    public function setVersionRegexp($var)
    {
        GPBUtil::checkString($var, True);
        $this->version_regexp = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string policy_id = 5 [json_name = "policyId", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @return RepeatedField<string>
     */
    public function getPolicyId()
    {
        return $this->policy_id;
    }

    /**
     * Generated from protobuf field <code>repeated string policy_id = 5 [json_name = "policyId", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @param string[] $var
     * @return $this
     */
    public function setPolicyId($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->policy_id = $arr;

        return $this;
    }

}

