<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cerbos/request/v1/request.proto

namespace Cerbos\Request\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>cerbos.request.v1.PlaygroundEvaluateRequest</code>
 */
class PlaygroundEvaluateRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string playground_id = 1 [json_name = "playgroundId"];</code>
     */
    protected $playground_id = '';
    /**
     * Generated from protobuf field <code>repeated .cerbos.request.v1.File files = 2 [json_name = "files", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     */
    private $files;
    /**
     * Generated from protobuf field <code>.cerbos.engine.v1.Principal principal = 3 [json_name = "principal", (.google.api.field_behavior) = REQUIRED, (.buf.validate.field) = {</code>
     */
    protected $principal = null;
    /**
     * Generated from protobuf field <code>.cerbos.engine.v1.Resource resource = 4 [json_name = "resource", (.google.api.field_behavior) = REQUIRED, (.buf.validate.field) = {</code>
     */
    protected $resource = null;
    /**
     * Generated from protobuf field <code>repeated string actions = 5 [json_name = "actions", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     */
    private $actions;
    /**
     * Generated from protobuf field <code>.cerbos.request.v1.AuxData aux_data = 6 [json_name = "auxData"];</code>
     */
    protected $aux_data = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $playground_id
     *     @type array<\Cerbos\Request\V1\File>|\Google\Protobuf\Internal\RepeatedField $files
     *     @type \Cerbos\Engine\V1\Principal $principal
     *     @type \Cerbos\Engine\V1\Resource $resource
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $actions
     *     @type \Cerbos\Request\V1\AuxData $aux_data
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Cerbos\Request\V1\Request::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string playground_id = 1 [json_name = "playgroundId"];</code>
     * @return string
     */
    public function getPlaygroundId()
    {
        return $this->playground_id;
    }

    /**
     * Generated from protobuf field <code>string playground_id = 1 [json_name = "playgroundId"];</code>
     * @param string $var
     * @return $this
     */
    public function setPlaygroundId($var)
    {
        GPBUtil::checkString($var, True);
        $this->playground_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .cerbos.request.v1.File files = 2 [json_name = "files", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getFiles()
    {
        return $this->files;
    }

    /**
     * Generated from protobuf field <code>repeated .cerbos.request.v1.File files = 2 [json_name = "files", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @param array<\Cerbos\Request\V1\File>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setFiles($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Cerbos\Request\V1\File::class);
        $this->files = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.cerbos.engine.v1.Principal principal = 3 [json_name = "principal", (.google.api.field_behavior) = REQUIRED, (.buf.validate.field) = {</code>
     * @return \Cerbos\Engine\V1\Principal|null
     */
    public function getPrincipal()
    {
        return $this->principal;
    }

    public function hasPrincipal()
    {
        return isset($this->principal);
    }

    public function clearPrincipal()
    {
        unset($this->principal);
    }

    /**
     * Generated from protobuf field <code>.cerbos.engine.v1.Principal principal = 3 [json_name = "principal", (.google.api.field_behavior) = REQUIRED, (.buf.validate.field) = {</code>
     * @param \Cerbos\Engine\V1\Principal $var
     * @return $this
     */
    public function setPrincipal($var)
    {
        GPBUtil::checkMessage($var, \Cerbos\Engine\V1\Principal::class);
        $this->principal = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.cerbos.engine.v1.Resource resource = 4 [json_name = "resource", (.google.api.field_behavior) = REQUIRED, (.buf.validate.field) = {</code>
     * @return \Cerbos\Engine\V1\Resource|null
     */
    public function getResource()
    {
        return $this->resource;
    }

    public function hasResource()
    {
        return isset($this->resource);
    }

    public function clearResource()
    {
        unset($this->resource);
    }

    /**
     * Generated from protobuf field <code>.cerbos.engine.v1.Resource resource = 4 [json_name = "resource", (.google.api.field_behavior) = REQUIRED, (.buf.validate.field) = {</code>
     * @param \Cerbos\Engine\V1\Resource $var
     * @return $this
     */
    public function setResource($var)
    {
        GPBUtil::checkMessage($var, \Cerbos\Engine\V1\Resource::class);
        $this->resource = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string actions = 5 [json_name = "actions", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getActions()
    {
        return $this->actions;
    }

    /**
     * Generated from protobuf field <code>repeated string actions = 5 [json_name = "actions", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setActions($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->actions = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.cerbos.request.v1.AuxData aux_data = 6 [json_name = "auxData"];</code>
     * @return \Cerbos\Request\V1\AuxData|null
     */
    public function getAuxData()
    {
        return $this->aux_data;
    }

    public function hasAuxData()
    {
        return isset($this->aux_data);
    }

    public function clearAuxData()
    {
        unset($this->aux_data);
    }

    /**
     * Generated from protobuf field <code>.cerbos.request.v1.AuxData aux_data = 6 [json_name = "auxData"];</code>
     * @param \Cerbos\Request\V1\AuxData $var
     * @return $this
     */
    public function setAuxData($var)
    {
        GPBUtil::checkMessage($var, \Cerbos\Request\V1\AuxData::class);
        $this->aux_data = $var;

        return $this;
    }

}

