<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cerbos/response/v1/response.proto

namespace Cerbos\Response\V1\PlaygroundFailure;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>cerbos.response.v1.PlaygroundFailure.ErrorDetails</code>
 */
class ErrorDetails extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 line = 1 [json_name = "line"];</code>
     */
    protected $line = 0;
    /**
     * Generated from protobuf field <code>uint32 column = 2 [json_name = "column"];</code>
     */
    protected $column = 0;
    /**
     * Generated from protobuf field <code>string context = 3 [json_name = "context"];</code>
     */
    protected $context = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $line
     *     @type int $column
     *     @type string $context
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Cerbos\Response\V1\Response::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint32 line = 1 [json_name = "line"];</code>
     * @return int
     */
    public function getLine()
    {
        return $this->line;
    }

    /**
     * Generated from protobuf field <code>uint32 line = 1 [json_name = "line"];</code>
     * @param int $var
     * @return $this
     */
    public function setLine($var)
    {
        GPBUtil::checkUint32($var);
        $this->line = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 column = 2 [json_name = "column"];</code>
     * @return int
     */
    public function getColumn()
    {
        return $this->column;
    }

    /**
     * Generated from protobuf field <code>uint32 column = 2 [json_name = "column"];</code>
     * @param int $var
     * @return $this
     */
    public function setColumn($var)
    {
        GPBUtil::checkUint32($var);
        $this->column = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string context = 3 [json_name = "context"];</code>
     * @return string
     */
    public function getContext()
    {
        return $this->context;
    }

    /**
     * Generated from protobuf field <code>string context = 3 [json_name = "context"];</code>
     * @param string $var
     * @return $this
     */
    public function setContext($var)
    {
        GPBUtil::checkString($var, True);
        $this->context = $var;

        return $this;
    }

}

