<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cerbos/audit/v1/audit.proto

namespace Cerbos\Audit\V1\PolicySource;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>cerbos.audit.v1.PolicySource.Database</code>
 */
class Database extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.cerbos.audit.v1.PolicySource.Database.Driver driver = 1 [json_name = "driver"];</code>
     */
    protected $driver = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $driver
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Cerbos\Audit\V1\Audit::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.cerbos.audit.v1.PolicySource.Database.Driver driver = 1 [json_name = "driver"];</code>
     * @return int
     */
    public function getDriver()
    {
        return $this->driver;
    }

    /**
     * Generated from protobuf field <code>.cerbos.audit.v1.PolicySource.Database.Driver driver = 1 [json_name = "driver"];</code>
     * @param int $var
     * @return $this
     */
    public function setDriver($var)
    {
        GPBUtil::checkEnum($var, \Cerbos\Audit\V1\PolicySource\Database\Driver::class);
        $this->driver = $var;

        return $this;
    }

}

