<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cerbos/audit/v1/audit.proto

namespace Cerbos\Audit\V1\PolicySource;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>cerbos.audit.v1.PolicySource.Disk</code>
 */
class Disk extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string directory = 1 [json_name = "directory"];</code>
     */
    protected $directory = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $directory
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Cerbos\Audit\V1\Audit::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string directory = 1 [json_name = "directory"];</code>
     * @return string
     */
    public function getDirectory()
    {
        return $this->directory;
    }

    /**
     * Generated from protobuf field <code>string directory = 1 [json_name = "directory"];</code>
     * @param string $var
     * @return $this
     */
    public function setDirectory($var)
    {
        GPBUtil::checkString($var, True);
        $this->directory = $var;

        return $this;
    }

}

