<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cerbos/cloud/pdp/v1/pdp.proto

namespace GPBMetadata\Cerbos\Cloud\Pdp\V1;

class Pdp
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            "\x0A\x88\x02\x0A\x1Dcerbos/cloud/pdp/v1/pdp.proto\x12\x13cerbos.cloud.pdp.v1\"T\x0A\x0AIdentifier\x12#\x0A\x08instance\x18\x01 \x01(\x09B\x07\xBAH\x04r\x02\x10\x01R\x08instance\x12!\x0A\x07version\x18\x02 \x01(\x09B\x07\xBAH\x04r\x02\x10\x01R\x07versionBt\x0A\x1Bdev.cerbos.api.cloud.v1.pdpZ;github.com/cerbos/cloud-api/genpb/cerbos/cloud/pdp/v1;pdpv1\xAA\x02\x17Cerbos.Api.Cloud.V1.Pdpb\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

