<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cerbos/schema/v1/schema.proto

namespace Cerbos\Schema\V1\ValidationError;

use UnexpectedValueException;

/**
 * Protobuf type <code>cerbos.schema.v1.ValidationError.Source</code>
 */
class Source
{
    /**
     * Generated from protobuf enum <code>SOURCE_UNSPECIFIED = 0;</code>
     */
    const SOURCE_UNSPECIFIED = 0;
    /**
     * Generated from protobuf enum <code>SOURCE_PRINCIPAL = 1;</code>
     */
    const SOURCE_PRINCIPAL = 1;
    /**
     * Generated from protobuf enum <code>SOURCE_RESOURCE = 2;</code>
     */
    const SOURCE_RESOURCE = 2;

    private static $valueToName = [
        self::SOURCE_UNSPECIFIED => 'SOURCE_UNSPECIFIED',
        self::SOURCE_PRINCIPAL => 'SOURCE_PRINCIPAL',
        self::SOURCE_RESOURCE => 'SOURCE_RESOURCE',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

