<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cerbos/policy/v1/policy.proto

namespace Cerbos\Policy\V1\TestResults\OutputFailure;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>cerbos.policy.v1.TestResults.OutputFailure.MismatchedValue</code>
 */
class MismatchedValue extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.google.protobuf.Value expected = 1 [json_name = "expected"];</code>
     */
    protected $expected = null;
    /**
     * Generated from protobuf field <code>.google.protobuf.Value actual = 2 [json_name = "actual"];</code>
     */
    protected $actual = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Google\Protobuf\Value $expected
     *     @type \Google\Protobuf\Value $actual
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Cerbos\Policy\V1\Policy::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Value expected = 1 [json_name = "expected"];</code>
     * @return \Google\Protobuf\Value|null
     */
    public function getExpected()
    {
        return $this->expected;
    }

    public function hasExpected()
    {
        return isset($this->expected);
    }

    public function clearExpected()
    {
        unset($this->expected);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Value expected = 1 [json_name = "expected"];</code>
     * @param \Google\Protobuf\Value $var
     * @return $this
     */
    public function setExpected($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Value::class);
        $this->expected = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Value actual = 2 [json_name = "actual"];</code>
     * @return \Google\Protobuf\Value|null
     */
    public function getActual()
    {
        return $this->actual;
    }

    public function hasActual()
    {
        return isset($this->actual);
    }

    public function clearActual()
    {
        unset($this->actual);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Value actual = 2 [json_name = "actual"];</code>
     * @param \Google\Protobuf\Value $var
     * @return $this
     */
    public function setActual($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Value::class);
        $this->actual = $var;

        return $this;
    }

}

