<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: validate/validate.proto

namespace Validate;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * AnyRules describe constraints applied exclusively to the
 * `google.protobuf.Any` well-known type
 *
 * Generated from protobuf message <code>validate.AnyRules</code>
 */
class AnyRules extends \Google\Protobuf\Internal\Message
{
    /**
     * Required specifies that this field must be set
     *
     * Generated from protobuf field <code>optional bool required = 1 [json_name = "required"];</code>
     */
    protected $required = null;
    /**
     * In specifies that this field's `type_url` must be equal to one of the
     * specified values.
     *
     * Generated from protobuf field <code>repeated string in = 2 [json_name = "in"];</code>
     */
    private $in;
    /**
     * NotIn specifies that this field's `type_url` must not be equal to any of
     * the specified values.
     *
     * Generated from protobuf field <code>repeated string not_in = 3 [json_name = "notIn"];</code>
     */
    private $not_in;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $required
     *           Required specifies that this field must be set
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $in
     *           In specifies that this field's `type_url` must be equal to one of the
     *           specified values.
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $not_in
     *           NotIn specifies that this field's `type_url` must not be equal to any of
     *           the specified values.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Validate\Validate::initOnce();
        parent::__construct($data);
    }

    /**
     * Required specifies that this field must be set
     *
     * Generated from protobuf field <code>optional bool required = 1 [json_name = "required"];</code>
     * @return bool
     */
    public function getRequired()
    {
        return isset($this->required) ? $this->required : false;
    }

    public function hasRequired()
    {
        return isset($this->required);
    }

    public function clearRequired()
    {
        unset($this->required);
    }

    /**
     * Required specifies that this field must be set
     *
     * Generated from protobuf field <code>optional bool required = 1 [json_name = "required"];</code>
     * @param bool $var
     * @return $this
     */
    public function setRequired($var)
    {
        GPBUtil::checkBool($var);
        $this->required = $var;

        return $this;
    }

    /**
     * In specifies that this field's `type_url` must be equal to one of the
     * specified values.
     *
     * Generated from protobuf field <code>repeated string in = 2 [json_name = "in"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getIn()
    {
        return $this->in;
    }

    /**
     * In specifies that this field's `type_url` must be equal to one of the
     * specified values.
     *
     * Generated from protobuf field <code>repeated string in = 2 [json_name = "in"];</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setIn($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->in = $arr;

        return $this;
    }

    /**
     * NotIn specifies that this field's `type_url` must not be equal to any of
     * the specified values.
     *
     * Generated from protobuf field <code>repeated string not_in = 3 [json_name = "notIn"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getNotIn()
    {
        return $this->not_in;
    }

    /**
     * NotIn specifies that this field's `type_url` must not be equal to any of
     * the specified values.
     *
     * Generated from protobuf field <code>repeated string not_in = 3 [json_name = "notIn"];</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setNotIn($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->not_in = $arr;

        return $this;
    }

}

