<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cerbos/telemetry/v1/telemetry.proto

namespace Cerbos\Telemetry\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>cerbos.telemetry.v1.ServerStop</code>
 */
class ServerStop extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string version = 1 [json_name = "version"];</code>
     */
    protected $version = '';
    /**
     * Generated from protobuf field <code>.google.protobuf.Duration uptime = 2 [json_name = "uptime"];</code>
     */
    protected $uptime = null;
    /**
     * Generated from protobuf field <code>uint64 requests_total = 3 [json_name = "requestsTotal"];</code>
     */
    protected $requests_total = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $version
     *     @type \Google\Protobuf\Duration $uptime
     *     @type int|string $requests_total
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Cerbos\Telemetry\V1\Telemetry::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string version = 1 [json_name = "version"];</code>
     * @return string
     */
    public function getVersion()
    {
        return $this->version;
    }

    /**
     * Generated from protobuf field <code>string version = 1 [json_name = "version"];</code>
     * @param string $var
     * @return $this
     */
    public function setVersion($var)
    {
        GPBUtil::checkString($var, True);
        $this->version = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Duration uptime = 2 [json_name = "uptime"];</code>
     * @return \Google\Protobuf\Duration|null
     */
    public function getUptime()
    {
        return $this->uptime;
    }

    public function hasUptime()
    {
        return isset($this->uptime);
    }

    public function clearUptime()
    {
        unset($this->uptime);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Duration uptime = 2 [json_name = "uptime"];</code>
     * @param \Google\Protobuf\Duration $var
     * @return $this
     */
    public function setUptime($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Duration::class);
        $this->uptime = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 requests_total = 3 [json_name = "requestsTotal"];</code>
     * @return int|string
     */
    public function getRequestsTotal()
    {
        return $this->requests_total;
    }

    /**
     * Generated from protobuf field <code>uint64 requests_total = 3 [json_name = "requestsTotal"];</code>
     * @param int|string $var
     * @return $this
     */
    public function setRequestsTotal($var)
    {
        GPBUtil::checkUint64($var);
        $this->requests_total = $var;

        return $this;
    }

}

