<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cerbos/audit/v1/audit.proto

namespace Cerbos\Audit\V1\DecisionLogEntry;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>cerbos.audit.v1.DecisionLogEntry.PlanResources</code>
 */
class PlanResources extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.cerbos.engine.v1.PlanResourcesInput input = 1 [json_name = "input"];</code>
     */
    protected $input = null;
    /**
     * Generated from protobuf field <code>.cerbos.engine.v1.PlanResourcesOutput output = 2 [json_name = "output"];</code>
     */
    protected $output = null;
    /**
     * Generated from protobuf field <code>string error = 3 [json_name = "error"];</code>
     */
    protected $error = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Cerbos\Engine\V1\PlanResourcesInput $input
     *     @type \Cerbos\Engine\V1\PlanResourcesOutput $output
     *     @type string $error
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Cerbos\Audit\V1\Audit::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.cerbos.engine.v1.PlanResourcesInput input = 1 [json_name = "input"];</code>
     * @return \Cerbos\Engine\V1\PlanResourcesInput|null
     */
    public function getInput()
    {
        return $this->input;
    }

    public function hasInput()
    {
        return isset($this->input);
    }

    public function clearInput()
    {
        unset($this->input);
    }

    /**
     * Generated from protobuf field <code>.cerbos.engine.v1.PlanResourcesInput input = 1 [json_name = "input"];</code>
     * @param \Cerbos\Engine\V1\PlanResourcesInput $var
     * @return $this
     */
    public function setInput($var)
    {
        GPBUtil::checkMessage($var, \Cerbos\Engine\V1\PlanResourcesInput::class);
        $this->input = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.cerbos.engine.v1.PlanResourcesOutput output = 2 [json_name = "output"];</code>
     * @return \Cerbos\Engine\V1\PlanResourcesOutput|null
     */
    public function getOutput()
    {
        return $this->output;
    }

    public function hasOutput()
    {
        return isset($this->output);
    }

    public function clearOutput()
    {
        unset($this->output);
    }

    /**
     * Generated from protobuf field <code>.cerbos.engine.v1.PlanResourcesOutput output = 2 [json_name = "output"];</code>
     * @param \Cerbos\Engine\V1\PlanResourcesOutput $var
     * @return $this
     */
    public function setOutput($var)
    {
        GPBUtil::checkMessage($var, \Cerbos\Engine\V1\PlanResourcesOutput::class);
        $this->output = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string error = 3 [json_name = "error"];</code>
     * @return string
     */
    public function getError()
    {
        return $this->error;
    }

    /**
     * Generated from protobuf field <code>string error = 3 [json_name = "error"];</code>
     * @param string $var
     * @return $this
     */
    public function setError($var)
    {
        GPBUtil::checkString($var, True);
        $this->error = $var;

        return $this;
    }

}

