<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cerbos/audit/v1/audit.proto

namespace Cerbos\Audit\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>cerbos.audit.v1.AccessLogEntry</code>
 */
class AccessLogEntry extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string call_id = 1 [json_name = "callId"];</code>
     */
    protected $call_id = '';
    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp timestamp = 2 [json_name = "timestamp"];</code>
     */
    protected $timestamp = null;
    /**
     * Generated from protobuf field <code>.cerbos.audit.v1.Peer peer = 3 [json_name = "peer"];</code>
     */
    protected $peer = null;
    /**
     * Generated from protobuf field <code>map<string, .cerbos.audit.v1.MetaValues> metadata = 4 [json_name = "metadata"];</code>
     */
    private $metadata;
    /**
     * Generated from protobuf field <code>string method = 5 [json_name = "method"];</code>
     */
    protected $method = '';
    /**
     * Generated from protobuf field <code>uint32 status_code = 6 [json_name = "statusCode"];</code>
     */
    protected $status_code = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $call_id
     *     @type \Google\Protobuf\Timestamp $timestamp
     *     @type \Cerbos\Audit\V1\Peer $peer
     *     @type array|\Google\Protobuf\Internal\MapField $metadata
     *     @type string $method
     *     @type int $status_code
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Cerbos\Audit\V1\Audit::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string call_id = 1 [json_name = "callId"];</code>
     * @return string
     */
    public function getCallId()
    {
        return $this->call_id;
    }

    /**
     * Generated from protobuf field <code>string call_id = 1 [json_name = "callId"];</code>
     * @param string $var
     * @return $this
     */
    public function setCallId($var)
    {
        GPBUtil::checkString($var, True);
        $this->call_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp timestamp = 2 [json_name = "timestamp"];</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getTimestamp()
    {
        return $this->timestamp;
    }

    public function hasTimestamp()
    {
        return isset($this->timestamp);
    }

    public function clearTimestamp()
    {
        unset($this->timestamp);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp timestamp = 2 [json_name = "timestamp"];</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setTimestamp($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->timestamp = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.cerbos.audit.v1.Peer peer = 3 [json_name = "peer"];</code>
     * @return \Cerbos\Audit\V1\Peer|null
     */
    public function getPeer()
    {
        return $this->peer;
    }

    public function hasPeer()
    {
        return isset($this->peer);
    }

    public function clearPeer()
    {
        unset($this->peer);
    }

    /**
     * Generated from protobuf field <code>.cerbos.audit.v1.Peer peer = 3 [json_name = "peer"];</code>
     * @param \Cerbos\Audit\V1\Peer $var
     * @return $this
     */
    public function setPeer($var)
    {
        GPBUtil::checkMessage($var, \Cerbos\Audit\V1\Peer::class);
        $this->peer = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>map<string, .cerbos.audit.v1.MetaValues> metadata = 4 [json_name = "metadata"];</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getMetadata()
    {
        return $this->metadata;
    }

    /**
     * Generated from protobuf field <code>map<string, .cerbos.audit.v1.MetaValues> metadata = 4 [json_name = "metadata"];</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setMetadata($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::MESSAGE, \Cerbos\Audit\V1\MetaValues::class);
        $this->metadata = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string method = 5 [json_name = "method"];</code>
     * @return string
     */
    public function getMethod()
    {
        return $this->method;
    }

    /**
     * Generated from protobuf field <code>string method = 5 [json_name = "method"];</code>
     * @param string $var
     * @return $this
     */
    public function setMethod($var)
    {
        GPBUtil::checkString($var, True);
        $this->method = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 status_code = 6 [json_name = "statusCode"];</code>
     * @return int
     */
    public function getStatusCode()
    {
        return $this->status_code;
    }

    /**
     * Generated from protobuf field <code>uint32 status_code = 6 [json_name = "statusCode"];</code>
     * @param int $var
     * @return $this
     */
    public function setStatusCode($var)
    {
        GPBUtil::checkUint32($var);
        $this->status_code = $var;

        return $this;
    }

}

