<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cerbos/audit/v1/audit.proto

namespace Cerbos\Audit\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>cerbos.audit.v1.Peer</code>
 */
class Peer extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string address = 1 [json_name = "address"];</code>
     */
    protected $address = '';
    /**
     * Generated from protobuf field <code>string auth_info = 2 [json_name = "authInfo"];</code>
     */
    protected $auth_info = '';
    /**
     * Generated from protobuf field <code>string user_agent = 3 [json_name = "userAgent"];</code>
     */
    protected $user_agent = '';
    /**
     * Generated from protobuf field <code>string forwarded_for = 4 [json_name = "forwardedFor"];</code>
     */
    protected $forwarded_for = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $address
     *     @type string $auth_info
     *     @type string $user_agent
     *     @type string $forwarded_for
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Cerbos\Audit\V1\Audit::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string address = 1 [json_name = "address"];</code>
     * @return string
     */
    public function getAddress()
    {
        return $this->address;
    }

    /**
     * Generated from protobuf field <code>string address = 1 [json_name = "address"];</code>
     * @param string $var
     * @return $this
     */
    public function setAddress($var)
    {
        GPBUtil::checkString($var, True);
        $this->address = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string auth_info = 2 [json_name = "authInfo"];</code>
     * @return string
     */
    public function getAuthInfo()
    {
        return $this->auth_info;
    }

    /**
     * Generated from protobuf field <code>string auth_info = 2 [json_name = "authInfo"];</code>
     * @param string $var
     * @return $this
     */
    public function setAuthInfo($var)
    {
        GPBUtil::checkString($var, True);
        $this->auth_info = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string user_agent = 3 [json_name = "userAgent"];</code>
     * @return string
     */
    public function getUserAgent()
    {
        return $this->user_agent;
    }

    /**
     * Generated from protobuf field <code>string user_agent = 3 [json_name = "userAgent"];</code>
     * @param string $var
     * @return $this
     */
    public function setUserAgent($var)
    {
        GPBUtil::checkString($var, True);
        $this->user_agent = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string forwarded_for = 4 [json_name = "forwardedFor"];</code>
     * @return string
     */
    public function getForwardedFor()
    {
        return $this->forwarded_for;
    }

    /**
     * Generated from protobuf field <code>string forwarded_for = 4 [json_name = "forwardedFor"];</code>
     * @param string $var
     * @return $this
     */
    public function setForwardedFor($var)
    {
        GPBUtil::checkString($var, True);
        $this->forwarded_for = $var;

        return $this;
    }

}

