<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cerbos/engine/v1/engine.proto

namespace Cerbos\Engine\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>cerbos.engine.v1.OutputEntry</code>
 */
class OutputEntry extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string src = 1 [json_name = "src", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     */
    protected $src = '';
    /**
     * Generated from protobuf field <code>.google.protobuf.Value val = 2 [json_name = "val", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     */
    protected $val = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $src
     *     @type \Google\Protobuf\Value $val
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Cerbos\Engine\V1\Engine::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string src = 1 [json_name = "src", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @return string
     */
    public function getSrc()
    {
        return $this->src;
    }

    /**
     * Generated from protobuf field <code>string src = 1 [json_name = "src", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @param string $var
     * @return $this
     */
    public function setSrc($var)
    {
        GPBUtil::checkString($var, True);
        $this->src = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Value val = 2 [json_name = "val", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @return \Google\Protobuf\Value|null
     */
    public function getVal()
    {
        return $this->val;
    }

    public function hasVal()
    {
        return isset($this->val);
    }

    public function clearVal()
    {
        unset($this->val);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Value val = 2 [json_name = "val", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @param \Google\Protobuf\Value $var
     * @return $this
     */
    public function setVal($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Value::class);
        $this->val = $var;

        return $this;
    }

}

