<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cerbos/engine/v1/engine.proto

namespace Cerbos\Engine\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>cerbos.engine.v1.PlanResourcesOutput</code>
 */
class PlanResourcesOutput extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string request_id = 1 [json_name = "requestId"];</code>
     */
    protected $request_id = '';
    /**
     * Generated from protobuf field <code>string action = 2 [json_name = "action", deprecated = true];</code>
     * @deprecated
     */
    protected $action = '';
    /**
     * Generated from protobuf field <code>string kind = 3 [json_name = "kind"];</code>
     */
    protected $kind = '';
    /**
     * Generated from protobuf field <code>string policy_version = 4 [json_name = "policyVersion"];</code>
     */
    protected $policy_version = '';
    /**
     * Generated from protobuf field <code>string scope = 5 [json_name = "scope"];</code>
     */
    protected $scope = '';
    /**
     * Generated from protobuf field <code>.cerbos.engine.v1.PlanResourcesFilter filter = 6 [json_name = "filter"];</code>
     */
    protected $filter = null;
    /**
     * Generated from protobuf field <code>string filter_debug = 7 [json_name = "filterDebug"];</code>
     */
    protected $filter_debug = '';
    /**
     * Generated from protobuf field <code>repeated .cerbos.schema.v1.ValidationError validation_errors = 8 [json_name = "validationErrors"];</code>
     */
    private $validation_errors;
    /**
     * Generated from protobuf field <code>repeated string actions = 9 [json_name = "actions"];</code>
     */
    private $actions;
    /**
     * Generated from protobuf field <code>map<string, string> matched_scopes = 10 [json_name = "matchedScopes"];</code>
     */
    private $matched_scopes;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $request_id
     *     @type string $action
     *     @type string $kind
     *     @type string $policy_version
     *     @type string $scope
     *     @type \Cerbos\Engine\V1\PlanResourcesFilter $filter
     *     @type string $filter_debug
     *     @type \Cerbos\Schema\V1\ValidationError[] $validation_errors
     *     @type string[] $actions
     *     @type array|\Google\Protobuf\Internal\MapField $matched_scopes
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Cerbos\Engine\V1\Engine::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string request_id = 1 [json_name = "requestId"];</code>
     * @return string
     */
    public function getRequestId()
    {
        return $this->request_id;
    }

    /**
     * Generated from protobuf field <code>string request_id = 1 [json_name = "requestId"];</code>
     * @param string $var
     * @return $this
     */
    public function setRequestId($var)
    {
        GPBUtil::checkString($var, True);
        $this->request_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string action = 2 [json_name = "action", deprecated = true];</code>
     * @return string
     * @deprecated
     */
    public function getAction()
    {
        if ($this->action !== '') {
            @trigger_error('action is deprecated.', E_USER_DEPRECATED);
        }
        return $this->action;
    }

    /**
     * Generated from protobuf field <code>string action = 2 [json_name = "action", deprecated = true];</code>
     * @param string $var
     * @return $this
     * @deprecated
     */
    public function setAction($var)
    {
        @trigger_error('action is deprecated.', E_USER_DEPRECATED);
        GPBUtil::checkString($var, True);
        $this->action = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string kind = 3 [json_name = "kind"];</code>
     * @return string
     */
    public function getKind()
    {
        return $this->kind;
    }

    /**
     * Generated from protobuf field <code>string kind = 3 [json_name = "kind"];</code>
     * @param string $var
     * @return $this
     */
    public function setKind($var)
    {
        GPBUtil::checkString($var, True);
        $this->kind = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string policy_version = 4 [json_name = "policyVersion"];</code>
     * @return string
     */
    public function getPolicyVersion()
    {
        return $this->policy_version;
    }

    /**
     * Generated from protobuf field <code>string policy_version = 4 [json_name = "policyVersion"];</code>
     * @param string $var
     * @return $this
     */
    public function setPolicyVersion($var)
    {
        GPBUtil::checkString($var, True);
        $this->policy_version = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string scope = 5 [json_name = "scope"];</code>
     * @return string
     */
    public function getScope()
    {
        return $this->scope;
    }

    /**
     * Generated from protobuf field <code>string scope = 5 [json_name = "scope"];</code>
     * @param string $var
     * @return $this
     */
    public function setScope($var)
    {
        GPBUtil::checkString($var, True);
        $this->scope = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.cerbos.engine.v1.PlanResourcesFilter filter = 6 [json_name = "filter"];</code>
     * @return \Cerbos\Engine\V1\PlanResourcesFilter|null
     */
    public function getFilter()
    {
        return $this->filter;
    }

    public function hasFilter()
    {
        return isset($this->filter);
    }

    public function clearFilter()
    {
        unset($this->filter);
    }

    /**
     * Generated from protobuf field <code>.cerbos.engine.v1.PlanResourcesFilter filter = 6 [json_name = "filter"];</code>
     * @param \Cerbos\Engine\V1\PlanResourcesFilter $var
     * @return $this
     */
    public function setFilter($var)
    {
        GPBUtil::checkMessage($var, \Cerbos\Engine\V1\PlanResourcesFilter::class);
        $this->filter = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string filter_debug = 7 [json_name = "filterDebug"];</code>
     * @return string
     */
    public function getFilterDebug()
    {
        return $this->filter_debug;
    }

    /**
     * Generated from protobuf field <code>string filter_debug = 7 [json_name = "filterDebug"];</code>
     * @param string $var
     * @return $this
     */
    public function setFilterDebug($var)
    {
        GPBUtil::checkString($var, True);
        $this->filter_debug = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .cerbos.schema.v1.ValidationError validation_errors = 8 [json_name = "validationErrors"];</code>
     * @return RepeatedField<\Cerbos\Schema\V1\ValidationError>
     */
    public function getValidationErrors()
    {
        return $this->validation_errors;
    }

    /**
     * Generated from protobuf field <code>repeated .cerbos.schema.v1.ValidationError validation_errors = 8 [json_name = "validationErrors"];</code>
     * @param \Cerbos\Schema\V1\ValidationError[] $var
     * @return $this
     */
    public function setValidationErrors($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Cerbos\Schema\V1\ValidationError::class);
        $this->validation_errors = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string actions = 9 [json_name = "actions"];</code>
     * @return RepeatedField<string>
     */
    public function getActions()
    {
        return $this->actions;
    }

    /**
     * Generated from protobuf field <code>repeated string actions = 9 [json_name = "actions"];</code>
     * @param string[] $var
     * @return $this
     */
    public function setActions($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->actions = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>map<string, string> matched_scopes = 10 [json_name = "matchedScopes"];</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getMatchedScopes()
    {
        return $this->matched_scopes;
    }

    /**
     * Generated from protobuf field <code>map<string, string> matched_scopes = 10 [json_name = "matchedScopes"];</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setMatchedScopes($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::STRING);
        $this->matched_scopes = $arr;

        return $this;
    }

}

