<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cerbos/engine/v1/engine.proto

namespace Cerbos\Engine\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Data from the request, provided to expressions as the top-level `request` variable.
 *
 * Generated from protobuf message <code>cerbos.engine.v1.Request</code>
 */
class Request extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.cerbos.engine.v1.Request.Principal principal = 1 [json_name = "principal"];</code>
     */
    protected $principal = null;
    /**
     * Generated from protobuf field <code>.cerbos.engine.v1.Request.Resource resource = 2 [json_name = "resource"];</code>
     */
    protected $resource = null;
    /**
     * Generated from protobuf field <code>.cerbos.engine.v1.AuxData aux_data = 3 [json_name = "auxData"];</code>
     */
    protected $aux_data = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Cerbos\Engine\V1\Request\Principal $principal
     *     @type \Cerbos\Engine\V1\Request\Resource $resource
     *     @type \Cerbos\Engine\V1\AuxData $aux_data
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Cerbos\Engine\V1\Engine::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.cerbos.engine.v1.Request.Principal principal = 1 [json_name = "principal"];</code>
     * @return \Cerbos\Engine\V1\Request\Principal|null
     */
    public function getPrincipal()
    {
        return $this->principal;
    }

    public function hasPrincipal()
    {
        return isset($this->principal);
    }

    public function clearPrincipal()
    {
        unset($this->principal);
    }

    /**
     * Generated from protobuf field <code>.cerbos.engine.v1.Request.Principal principal = 1 [json_name = "principal"];</code>
     * @param \Cerbos\Engine\V1\Request\Principal $var
     * @return $this
     */
    public function setPrincipal($var)
    {
        GPBUtil::checkMessage($var, \Cerbos\Engine\V1\Request\Principal::class);
        $this->principal = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.cerbos.engine.v1.Request.Resource resource = 2 [json_name = "resource"];</code>
     * @return \Cerbos\Engine\V1\Request\Resource|null
     */
    public function getResource()
    {
        return $this->resource;
    }

    public function hasResource()
    {
        return isset($this->resource);
    }

    public function clearResource()
    {
        unset($this->resource);
    }

    /**
     * Generated from protobuf field <code>.cerbos.engine.v1.Request.Resource resource = 2 [json_name = "resource"];</code>
     * @param \Cerbos\Engine\V1\Request\Resource $var
     * @return $this
     */
    public function setResource($var)
    {
        GPBUtil::checkMessage($var, \Cerbos\Engine\V1\Request\Resource::class);
        $this->resource = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.cerbos.engine.v1.AuxData aux_data = 3 [json_name = "auxData"];</code>
     * @return \Cerbos\Engine\V1\AuxData|null
     */
    public function getAuxData()
    {
        return $this->aux_data;
    }

    public function hasAuxData()
    {
        return isset($this->aux_data);
    }

    public function clearAuxData()
    {
        unset($this->aux_data);
    }

    /**
     * Generated from protobuf field <code>.cerbos.engine.v1.AuxData aux_data = 3 [json_name = "auxData"];</code>
     * @param \Cerbos\Engine\V1\AuxData $var
     * @return $this
     */
    public function setAuxData($var)
    {
        GPBUtil::checkMessage($var, \Cerbos\Engine\V1\AuxData::class);
        $this->aux_data = $var;

        return $this;
    }

}

