<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cerbos/engine/v1/engine.proto

namespace Cerbos\Engine\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Data from the runtime, provided to expressions as the top-level `runtime` variable.
 *
 * Generated from protobuf message <code>cerbos.engine.v1.Runtime</code>
 */
class Runtime extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated string effective_derived_roles = 1 [json_name = "effectiveDerivedRoles"];</code>
     */
    private $effective_derived_roles;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $effective_derived_roles
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Cerbos\Engine\V1\Engine::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated string effective_derived_roles = 1 [json_name = "effectiveDerivedRoles"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getEffectiveDerivedRoles()
    {
        return $this->effective_derived_roles;
    }

    /**
     * Generated from protobuf field <code>repeated string effective_derived_roles = 1 [json_name = "effectiveDerivedRoles"];</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setEffectiveDerivedRoles($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->effective_derived_roles = $arr;

        return $this;
    }

}

