<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cerbos/engine/v1/engine.proto

namespace Cerbos\Engine\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>cerbos.engine.v1.TraceBatch</code>
 */
class TraceBatch extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .cerbos.engine.v1.Trace.Component definitions = 1 [json_name = "definitions"];</code>
     */
    private $definitions;
    /**
     * Generated from protobuf field <code>repeated .cerbos.engine.v1.TraceEntry entries = 2 [json_name = "entries"];</code>
     */
    private $entries;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Cerbos\Engine\V1\Trace\Component[] $definitions
     *     @type \Cerbos\Engine\V1\TraceEntry[] $entries
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Cerbos\Engine\V1\Engine::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .cerbos.engine.v1.Trace.Component definitions = 1 [json_name = "definitions"];</code>
     * @return RepeatedField<\Cerbos\Engine\V1\Trace\Component>
     */
    public function getDefinitions()
    {
        return $this->definitions;
    }

    /**
     * Generated from protobuf field <code>repeated .cerbos.engine.v1.Trace.Component definitions = 1 [json_name = "definitions"];</code>
     * @param \Cerbos\Engine\V1\Trace\Component[] $var
     * @return $this
     */
    public function setDefinitions($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Cerbos\Engine\V1\Trace\Component::class);
        $this->definitions = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .cerbos.engine.v1.TraceEntry entries = 2 [json_name = "entries"];</code>
     * @return RepeatedField<\Cerbos\Engine\V1\TraceEntry>
     */
    public function getEntries()
    {
        return $this->entries;
    }

    /**
     * Generated from protobuf field <code>repeated .cerbos.engine.v1.TraceEntry entries = 2 [json_name = "entries"];</code>
     * @param \Cerbos\Engine\V1\TraceEntry[] $var
     * @return $this
     */
    public function setEntries($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Cerbos\Engine\V1\TraceEntry::class);
        $this->entries = $arr;

        return $this;
    }

}

