<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cerbos/policy/v1/policy.proto

namespace Cerbos\Policy\V1\TestResults;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>cerbos.policy.v1.TestResults.Failure</code>
 */
class Failure extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.cerbos.effect.v1.Effect expected = 1 [json_name = "expected"];</code>
     */
    protected $expected = 0;
    /**
     * Generated from protobuf field <code>.cerbos.effect.v1.Effect actual = 2 [json_name = "actual"];</code>
     */
    protected $actual = 0;
    /**
     * Generated from protobuf field <code>repeated .cerbos.policy.v1.TestResults.OutputFailure outputs = 3 [json_name = "outputs"];</code>
     */
    private $outputs;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $expected
     *     @type int $actual
     *     @type \Cerbos\Policy\V1\TestResults\OutputFailure[] $outputs
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Cerbos\Policy\V1\Policy::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.cerbos.effect.v1.Effect expected = 1 [json_name = "expected"];</code>
     * @return int
     */
    public function getExpected()
    {
        return $this->expected;
    }

    /**
     * Generated from protobuf field <code>.cerbos.effect.v1.Effect expected = 1 [json_name = "expected"];</code>
     * @param int $var
     * @return $this
     */
    public function setExpected($var)
    {
        GPBUtil::checkEnum($var, \Cerbos\Effect\V1\Effect::class);
        $this->expected = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.cerbos.effect.v1.Effect actual = 2 [json_name = "actual"];</code>
     * @return int
     */
    public function getActual()
    {
        return $this->actual;
    }

    /**
     * Generated from protobuf field <code>.cerbos.effect.v1.Effect actual = 2 [json_name = "actual"];</code>
     * @param int $var
     * @return $this
     */
    public function setActual($var)
    {
        GPBUtil::checkEnum($var, \Cerbos\Effect\V1\Effect::class);
        $this->actual = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .cerbos.policy.v1.TestResults.OutputFailure outputs = 3 [json_name = "outputs"];</code>
     * @return RepeatedField<\Cerbos\Policy\V1\TestResults\OutputFailure>
     */
    public function getOutputs()
    {
        return $this->outputs;
    }

    /**
     * Generated from protobuf field <code>repeated .cerbos.policy.v1.TestResults.OutputFailure outputs = 3 [json_name = "outputs"];</code>
     * @param \Cerbos\Policy\V1\TestResults\OutputFailure[] $var
     * @return $this
     */
    public function setOutputs($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Cerbos\Policy\V1\TestResults\OutputFailure::class);
        $this->outputs = $arr;

        return $this;
    }

}

