<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cerbos/policy/v1/policy.proto

namespace Cerbos\Policy\V1\TestTable;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>cerbos.policy.v1.TestTable.Expectation</code>
 */
class Expectation extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string principal = 1 [json_name = "principal", (.buf.validate.field) = {</code>
     */
    protected $principal = '';
    /**
     * Generated from protobuf field <code>string resource = 2 [json_name = "resource", (.buf.validate.field) = {</code>
     */
    protected $resource = '';
    /**
     * Generated from protobuf field <code>map<string, .cerbos.effect.v1.Effect> actions = 3 [json_name = "actions", (.buf.validate.field) = {</code>
     */
    private $actions;
    /**
     * Generated from protobuf field <code>repeated .cerbos.policy.v1.TestTable.OutputExpectations outputs = 4 [json_name = "outputs"];</code>
     */
    private $outputs;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $principal
     *     @type string $resource
     *     @type array|\Google\Protobuf\Internal\MapField $actions
     *     @type array<\Cerbos\Policy\V1\TestTable\OutputExpectations>|\Google\Protobuf\Internal\RepeatedField $outputs
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Cerbos\Policy\V1\Policy::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string principal = 1 [json_name = "principal", (.buf.validate.field) = {</code>
     * @return string
     */
    public function getPrincipal()
    {
        return $this->principal;
    }

    /**
     * Generated from protobuf field <code>string principal = 1 [json_name = "principal", (.buf.validate.field) = {</code>
     * @param string $var
     * @return $this
     */
    public function setPrincipal($var)
    {
        GPBUtil::checkString($var, True);
        $this->principal = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string resource = 2 [json_name = "resource", (.buf.validate.field) = {</code>
     * @return string
     */
    public function getResource()
    {
        return $this->resource;
    }

    /**
     * Generated from protobuf field <code>string resource = 2 [json_name = "resource", (.buf.validate.field) = {</code>
     * @param string $var
     * @return $this
     */
    public function setResource($var)
    {
        GPBUtil::checkString($var, True);
        $this->resource = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>map<string, .cerbos.effect.v1.Effect> actions = 3 [json_name = "actions", (.buf.validate.field) = {</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getActions()
    {
        return $this->actions;
    }

    /**
     * Generated from protobuf field <code>map<string, .cerbos.effect.v1.Effect> actions = 3 [json_name = "actions", (.buf.validate.field) = {</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setActions($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::ENUM, \Cerbos\Effect\V1\Effect::class);
        $this->actions = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .cerbos.policy.v1.TestTable.OutputExpectations outputs = 4 [json_name = "outputs"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getOutputs()
    {
        return $this->outputs;
    }

    /**
     * Generated from protobuf field <code>repeated .cerbos.policy.v1.TestTable.OutputExpectations outputs = 4 [json_name = "outputs"];</code>
     * @param array<\Cerbos\Policy\V1\TestTable\OutputExpectations>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setOutputs($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Cerbos\Policy\V1\TestTable\OutputExpectations::class);
        $this->outputs = $arr;

        return $this;
    }

}

