<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cerbos/policy/v1/policy.proto

namespace Cerbos\Policy\V1\Test;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>cerbos.policy.v1.Test.TestName</code>
 */
class TestName extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string test_table_name = 1 [json_name = "testTableName"];</code>
     */
    protected $test_table_name = '';
    /**
     * Generated from protobuf field <code>string principal_key = 2 [json_name = "principalKey"];</code>
     */
    protected $principal_key = '';
    /**
     * Generated from protobuf field <code>string resource_key = 3 [json_name = "resourceKey"];</code>
     */
    protected $resource_key = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $test_table_name
     *     @type string $principal_key
     *     @type string $resource_key
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Cerbos\Policy\V1\Policy::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string test_table_name = 1 [json_name = "testTableName"];</code>
     * @return string
     */
    public function getTestTableName()
    {
        return $this->test_table_name;
    }

    /**
     * Generated from protobuf field <code>string test_table_name = 1 [json_name = "testTableName"];</code>
     * @param string $var
     * @return $this
     */
    public function setTestTableName($var)
    {
        GPBUtil::checkString($var, True);
        $this->test_table_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string principal_key = 2 [json_name = "principalKey"];</code>
     * @return string
     */
    public function getPrincipalKey()
    {
        return $this->principal_key;
    }

    /**
     * Generated from protobuf field <code>string principal_key = 2 [json_name = "principalKey"];</code>
     * @param string $var
     * @return $this
     */
    public function setPrincipalKey($var)
    {
        GPBUtil::checkString($var, True);
        $this->principal_key = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string resource_key = 3 [json_name = "resourceKey"];</code>
     * @return string
     */
    public function getResourceKey()
    {
        return $this->resource_key;
    }

    /**
     * Generated from protobuf field <code>string resource_key = 3 [json_name = "resourceKey"];</code>
     * @param string $var
     * @return $this
     */
    public function setResourceKey($var)
    {
        GPBUtil::checkString($var, True);
        $this->resource_key = $var;

        return $this;
    }

}

