<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cerbos/response/v1/response.proto

namespace Cerbos\Response\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>cerbos.response.v1.DeletePolicyResponse</code>
 */
class DeletePolicyResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 deleted_policies = 1 [json_name = "deletedPolicies"];</code>
     */
    protected $deleted_policies = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $deleted_policies
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Cerbos\Response\V1\Response::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint32 deleted_policies = 1 [json_name = "deletedPolicies"];</code>
     * @return int
     */
    public function getDeletedPolicies()
    {
        return $this->deleted_policies;
    }

    /**
     * Generated from protobuf field <code>uint32 deleted_policies = 1 [json_name = "deletedPolicies"];</code>
     * @param int $var
     * @return $this
     */
    public function setDeletedPolicies($var)
    {
        GPBUtil::checkUint32($var);
        $this->deleted_policies = $var;

        return $this;
    }

}

