<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cerbos/response/v1/response.proto

namespace Cerbos\Response\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>cerbos.response.v1.GetSchemaResponse</code>
 */
class GetSchemaResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .cerbos.schema.v1.Schema schemas = 1 [json_name = "schemas"];</code>
     */
    private $schemas;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Cerbos\Schema\V1\Schema[] $schemas
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Cerbos\Response\V1\Response::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .cerbos.schema.v1.Schema schemas = 1 [json_name = "schemas"];</code>
     * @return RepeatedField<\Cerbos\Schema\V1\Schema>
     */
    public function getSchemas()
    {
        return $this->schemas;
    }

    /**
     * Generated from protobuf field <code>repeated .cerbos.schema.v1.Schema schemas = 1 [json_name = "schemas"];</code>
     * @param \Cerbos\Schema\V1\Schema[] $var
     * @return $this
     */
    public function setSchemas($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Cerbos\Schema\V1\Schema::class);
        $this->schemas = $arr;

        return $this;
    }

}

