<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cerbos/response/v1/response.proto

namespace Cerbos\Response\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>cerbos.response.v1.PlaygroundProxyResponse</code>
 */
class PlaygroundProxyResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string playground_id = 1 [json_name = "playgroundId"];</code>
     */
    protected $playground_id = '';
    protected $outcome;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $playground_id
     *     @type \Cerbos\Response\V1\PlaygroundFailure $failure
     *     @type \Cerbos\Response\V1\CheckResourceSetResponse $check_resource_set
     *     @type \Cerbos\Response\V1\CheckResourceBatchResponse $check_resource_batch
     *     @type \Cerbos\Response\V1\PlanResourcesResponse $plan_resources
     *     @type \Cerbos\Response\V1\CheckResourcesResponse $check_resources
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Cerbos\Response\V1\Response::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string playground_id = 1 [json_name = "playgroundId"];</code>
     * @return string
     */
    public function getPlaygroundId()
    {
        return $this->playground_id;
    }

    /**
     * Generated from protobuf field <code>string playground_id = 1 [json_name = "playgroundId"];</code>
     * @param string $var
     * @return $this
     */
    public function setPlaygroundId($var)
    {
        GPBUtil::checkString($var, True);
        $this->playground_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.cerbos.response.v1.PlaygroundFailure failure = 2 [json_name = "failure"];</code>
     * @return \Cerbos\Response\V1\PlaygroundFailure|null
     */
    public function getFailure()
    {
        return $this->readOneof(2);
    }

    public function hasFailure()
    {
        return $this->hasOneof(2);
    }

    /**
     * Generated from protobuf field <code>.cerbos.response.v1.PlaygroundFailure failure = 2 [json_name = "failure"];</code>
     * @param \Cerbos\Response\V1\PlaygroundFailure $var
     * @return $this
     */
    public function setFailure($var)
    {
        GPBUtil::checkMessage($var, \Cerbos\Response\V1\PlaygroundFailure::class);
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.cerbos.response.v1.CheckResourceSetResponse check_resource_set = 3 [json_name = "checkResourceSet"];</code>
     * @return \Cerbos\Response\V1\CheckResourceSetResponse|null
     */
    public function getCheckResourceSet()
    {
        return $this->readOneof(3);
    }

    public function hasCheckResourceSet()
    {
        return $this->hasOneof(3);
    }

    /**
     * Generated from protobuf field <code>.cerbos.response.v1.CheckResourceSetResponse check_resource_set = 3 [json_name = "checkResourceSet"];</code>
     * @param \Cerbos\Response\V1\CheckResourceSetResponse $var
     * @return $this
     */
    public function setCheckResourceSet($var)
    {
        GPBUtil::checkMessage($var, \Cerbos\Response\V1\CheckResourceSetResponse::class);
        $this->writeOneof(3, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.cerbos.response.v1.CheckResourceBatchResponse check_resource_batch = 4 [json_name = "checkResourceBatch"];</code>
     * @return \Cerbos\Response\V1\CheckResourceBatchResponse|null
     */
    public function getCheckResourceBatch()
    {
        return $this->readOneof(4);
    }

    public function hasCheckResourceBatch()
    {
        return $this->hasOneof(4);
    }

    /**
     * Generated from protobuf field <code>.cerbos.response.v1.CheckResourceBatchResponse check_resource_batch = 4 [json_name = "checkResourceBatch"];</code>
     * @param \Cerbos\Response\V1\CheckResourceBatchResponse $var
     * @return $this
     */
    public function setCheckResourceBatch($var)
    {
        GPBUtil::checkMessage($var, \Cerbos\Response\V1\CheckResourceBatchResponse::class);
        $this->writeOneof(4, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.cerbos.response.v1.PlanResourcesResponse plan_resources = 5 [json_name = "planResources"];</code>
     * @return \Cerbos\Response\V1\PlanResourcesResponse|null
     */
    public function getPlanResources()
    {
        return $this->readOneof(5);
    }

    public function hasPlanResources()
    {
        return $this->hasOneof(5);
    }

    /**
     * Generated from protobuf field <code>.cerbos.response.v1.PlanResourcesResponse plan_resources = 5 [json_name = "planResources"];</code>
     * @param \Cerbos\Response\V1\PlanResourcesResponse $var
     * @return $this
     */
    public function setPlanResources($var)
    {
        GPBUtil::checkMessage($var, \Cerbos\Response\V1\PlanResourcesResponse::class);
        $this->writeOneof(5, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.cerbos.response.v1.CheckResourcesResponse check_resources = 6 [json_name = "checkResources"];</code>
     * @return \Cerbos\Response\V1\CheckResourcesResponse|null
     */
    public function getCheckResources()
    {
        return $this->readOneof(6);
    }

    public function hasCheckResources()
    {
        return $this->hasOneof(6);
    }

    /**
     * Generated from protobuf field <code>.cerbos.response.v1.CheckResourcesResponse check_resources = 6 [json_name = "checkResources"];</code>
     * @param \Cerbos\Response\V1\CheckResourcesResponse $var
     * @return $this
     */
    public function setCheckResources($var)
    {
        GPBUtil::checkMessage($var, \Cerbos\Response\V1\CheckResourcesResponse::class);
        $this->writeOneof(6, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getOutcome()
    {
        return $this->whichOneof("outcome");
    }

}

