<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: buf/validate/validate.proto

namespace Buf\Validate;

use UnexpectedValueException;

/**
 * WellKnownRegex contain some well-known patterns.
 *
 * Protobuf type <code>buf.validate.KnownRegex</code>
 */
class KnownRegex
{
    /**
     * Generated from protobuf enum <code>KNOWN_REGEX_UNSPECIFIED = 0;</code>
     */
    const KNOWN_REGEX_UNSPECIFIED = 0;
    /**
     * HTTP header name as defined by [RFC 7230](https://tools.ietf.org/html/rfc7230#section-3.2).
     *
     * Generated from protobuf enum <code>KNOWN_REGEX_HTTP_HEADER_NAME = 1;</code>
     */
    const KNOWN_REGEX_HTTP_HEADER_NAME = 1;
    /**
     * HTTP header value as defined by [RFC 7230](https://tools.ietf.org/html/rfc7230#section-3.2.4).
     *
     * Generated from protobuf enum <code>KNOWN_REGEX_HTTP_HEADER_VALUE = 2;</code>
     */
    const KNOWN_REGEX_HTTP_HEADER_VALUE = 2;

    private static $valueToName = [
        self::KNOWN_REGEX_UNSPECIFIED => 'KNOWN_REGEX_UNSPECIFIED',
        self::KNOWN_REGEX_HTTP_HEADER_NAME => 'KNOWN_REGEX_HTTP_HEADER_NAME',
        self::KNOWN_REGEX_HTTP_HEADER_VALUE => 'KNOWN_REGEX_HTTP_HEADER_VALUE',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

