<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cerbos/cloud/bundle/v2/bundle.proto

namespace Cerbos\Cloud\Bundle\V2\BundleInfo;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>cerbos.cloud.bundle.v2.BundleInfo.Segment</code>
 */
class Segment extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 segment_id = 1 [json_name = "segmentId"];</code>
     */
    protected $segment_id = 0;
    /**
     * Generated from protobuf field <code>bytes checksum = 2 [json_name = "checksum"];</code>
     */
    protected $checksum = '';
    /**
     * Generated from protobuf field <code>repeated string download_urls = 3 [json_name = "downloadUrls"];</code>
     */
    private $download_urls;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $segment_id
     *     @type string $checksum
     *     @type string[] $download_urls
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Cerbos\Cloud\Bundle\V2\Bundle::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint32 segment_id = 1 [json_name = "segmentId"];</code>
     * @return int
     */
    public function getSegmentId()
    {
        return $this->segment_id;
    }

    /**
     * Generated from protobuf field <code>uint32 segment_id = 1 [json_name = "segmentId"];</code>
     * @param int $var
     * @return $this
     */
    public function setSegmentId($var)
    {
        GPBUtil::checkUint32($var);
        $this->segment_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes checksum = 2 [json_name = "checksum"];</code>
     * @return string
     */
    public function getChecksum()
    {
        return $this->checksum;
    }

    /**
     * Generated from protobuf field <code>bytes checksum = 2 [json_name = "checksum"];</code>
     * @param string $var
     * @return $this
     */
    public function setChecksum($var)
    {
        GPBUtil::checkString($var, False);
        $this->checksum = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string download_urls = 3 [json_name = "downloadUrls"];</code>
     * @return RepeatedField<string>
     */
    public function getDownloadUrls()
    {
        return $this->download_urls;
    }

    /**
     * Generated from protobuf field <code>repeated string download_urls = 3 [json_name = "downloadUrls"];</code>
     * @param string[] $var
     * @return $this
     */
    public function setDownloadUrls($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->download_urls = $arr;

        return $this;
    }

}

