<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cerbos/cloud/pdp/v1/pdp.proto

namespace Cerbos\Cloud\Pdp\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>cerbos.cloud.pdp.v1.Identifier</code>
 */
class Identifier extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string instance = 1 [json_name = "instance"];</code>
     */
    protected $instance = '';
    /**
     * Generated from protobuf field <code>string version = 2 [json_name = "version"];</code>
     */
    protected $version = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $instance
     *     @type string $version
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Cerbos\Cloud\Pdp\V1\Pdp::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string instance = 1 [json_name = "instance"];</code>
     * @return string
     */
    public function getInstance()
    {
        return $this->instance;
    }

    /**
     * Generated from protobuf field <code>string instance = 1 [json_name = "instance"];</code>
     * @param string $var
     * @return $this
     */
    public function setInstance($var)
    {
        GPBUtil::checkString($var, True);
        $this->instance = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string version = 2 [json_name = "version"];</code>
     * @return string
     */
    public function getVersion()
    {
        return $this->version;
    }

    /**
     * Generated from protobuf field <code>string version = 2 [json_name = "version"];</code>
     * @param string $var
     * @return $this
     */
    public function setVersion($var)
    {
        GPBUtil::checkString($var, True);
        $this->version = $var;

        return $this;
    }

}

