<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cerbos/response/v1/response.proto

namespace Cerbos\Response\V1\PlaygroundEvaluateResponse;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>cerbos.response.v1.PlaygroundEvaluateResponse.EvalResultList</code>
 */
class EvalResultList extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .cerbos.response.v1.PlaygroundEvaluateResponse.EvalResult results = 1 [json_name = "results"];</code>
     */
    private $results;
    /**
     * Generated from protobuf field <code>repeated string effective_derived_roles = 2 [json_name = "effectiveDerivedRoles"];</code>
     */
    private $effective_derived_roles;
    /**
     * Generated from protobuf field <code>repeated .cerbos.schema.v1.ValidationError validation_errors = 3 [json_name = "validationErrors"];</code>
     */
    private $validation_errors;
    /**
     * Generated from protobuf field <code>repeated .cerbos.engine.v1.OutputEntry outputs = 4 [json_name = "outputs"];</code>
     */
    private $outputs;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<\Cerbos\Response\V1\PlaygroundEvaluateResponse\EvalResult>|\Google\Protobuf\Internal\RepeatedField $results
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $effective_derived_roles
     *     @type array<\Cerbos\Schema\V1\ValidationError>|\Google\Protobuf\Internal\RepeatedField $validation_errors
     *     @type array<\Cerbos\Engine\V1\OutputEntry>|\Google\Protobuf\Internal\RepeatedField $outputs
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Cerbos\Response\V1\Response::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .cerbos.response.v1.PlaygroundEvaluateResponse.EvalResult results = 1 [json_name = "results"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getResults()
    {
        return $this->results;
    }

    /**
     * Generated from protobuf field <code>repeated .cerbos.response.v1.PlaygroundEvaluateResponse.EvalResult results = 1 [json_name = "results"];</code>
     * @param array<\Cerbos\Response\V1\PlaygroundEvaluateResponse\EvalResult>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setResults($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Cerbos\Response\V1\PlaygroundEvaluateResponse\EvalResult::class);
        $this->results = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string effective_derived_roles = 2 [json_name = "effectiveDerivedRoles"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getEffectiveDerivedRoles()
    {
        return $this->effective_derived_roles;
    }

    /**
     * Generated from protobuf field <code>repeated string effective_derived_roles = 2 [json_name = "effectiveDerivedRoles"];</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setEffectiveDerivedRoles($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->effective_derived_roles = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .cerbos.schema.v1.ValidationError validation_errors = 3 [json_name = "validationErrors"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getValidationErrors()
    {
        return $this->validation_errors;
    }

    /**
     * Generated from protobuf field <code>repeated .cerbos.schema.v1.ValidationError validation_errors = 3 [json_name = "validationErrors"];</code>
     * @param array<\Cerbos\Schema\V1\ValidationError>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setValidationErrors($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Cerbos\Schema\V1\ValidationError::class);
        $this->validation_errors = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .cerbos.engine.v1.OutputEntry outputs = 4 [json_name = "outputs"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getOutputs()
    {
        return $this->outputs;
    }

    /**
     * Generated from protobuf field <code>repeated .cerbos.engine.v1.OutputEntry outputs = 4 [json_name = "outputs"];</code>
     * @param array<\Cerbos\Engine\V1\OutputEntry>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setOutputs($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Cerbos\Engine\V1\OutputEntry::class);
        $this->outputs = $arr;

        return $this;
    }

}

