<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cerbos/telemetry/v1/telemetry.proto

namespace Cerbos\Telemetry\V1\ServerLaunch\Features\Storage;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>cerbos.telemetry.v1.ServerLaunch.Features.Storage.Bundle</code>
 */
class Bundle extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string pdp_id = 1 [json_name = "pdpId"];</code>
     */
    protected $pdp_id = '';
    /**
     * Generated from protobuf field <code>string bundle_source = 2 [json_name = "bundleSource"];</code>
     */
    protected $bundle_source = '';
    /**
     * Generated from protobuf field <code>string client_id = 3 [json_name = "clientId"];</code>
     */
    protected $client_id = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $pdp_id
     *     @type string $bundle_source
     *     @type string $client_id
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Cerbos\Telemetry\V1\Telemetry::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string pdp_id = 1 [json_name = "pdpId"];</code>
     * @return string
     */
    public function getPdpId()
    {
        return $this->pdp_id;
    }

    /**
     * Generated from protobuf field <code>string pdp_id = 1 [json_name = "pdpId"];</code>
     * @param string $var
     * @return $this
     */
    public function setPdpId($var)
    {
        GPBUtil::checkString($var, True);
        $this->pdp_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string bundle_source = 2 [json_name = "bundleSource"];</code>
     * @return string
     */
    public function getBundleSource()
    {
        return $this->bundle_source;
    }

    /**
     * Generated from protobuf field <code>string bundle_source = 2 [json_name = "bundleSource"];</code>
     * @param string $var
     * @return $this
     */
    public function setBundleSource($var)
    {
        GPBUtil::checkString($var, True);
        $this->bundle_source = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string client_id = 3 [json_name = "clientId"];</code>
     * @return string
     */
    public function getClientId()
    {
        return $this->client_id;
    }

    /**
     * Generated from protobuf field <code>string client_id = 3 [json_name = "clientId"];</code>
     * @param string $var
     * @return $this
     */
    public function setClientId($var)
    {
        GPBUtil::checkString($var, True);
        $this->client_id = $var;

        return $this;
    }

}

