<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cerbos/telemetry/v1/telemetry.proto

namespace Cerbos\Telemetry\V1\ServerLaunch\Features\Storage;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>cerbos.telemetry.v1.ServerLaunch.Features.Storage.Disk</code>
 */
class Disk extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bool watch = 1 [json_name = "watch"];</code>
     */
    protected $watch = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $watch
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Cerbos\Telemetry\V1\Telemetry::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bool watch = 1 [json_name = "watch"];</code>
     * @return bool
     */
    public function getWatch()
    {
        return $this->watch;
    }

    /**
     * Generated from protobuf field <code>bool watch = 1 [json_name = "watch"];</code>
     * @param bool $var
     * @return $this
     */
    public function setWatch($var)
    {
        GPBUtil::checkBool($var);
        $this->watch = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Disk::class, \Cerbos\Telemetry\V1\ServerLaunch_Features_Storage_Disk::class);

