<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cerbos/policy/v1/policy.proto

namespace Cerbos\Policy\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>cerbos.policy.v1.DerivedRoles</code>
 */
class DerivedRoles extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string name = 1 [json_name = "name", (.buf.validate.field) = {</code>
     */
    protected $name = '';
    /**
     * Generated from protobuf field <code>repeated .cerbos.policy.v1.RoleDef definitions = 2 [json_name = "definitions", (.buf.validate.field) = {</code>
     */
    private $definitions;
    /**
     * Generated from protobuf field <code>.cerbos.policy.v1.Variables variables = 3 [json_name = "variables"];</code>
     */
    protected $variables = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *     @type array<\Cerbos\Policy\V1\RoleDef>|\Google\Protobuf\Internal\RepeatedField $definitions
     *     @type \Cerbos\Policy\V1\Variables $variables
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Cerbos\Policy\V1\Policy::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string name = 1 [json_name = "name", (.buf.validate.field) = {</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 1 [json_name = "name", (.buf.validate.field) = {</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .cerbos.policy.v1.RoleDef definitions = 2 [json_name = "definitions", (.buf.validate.field) = {</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getDefinitions()
    {
        return $this->definitions;
    }

    /**
     * Generated from protobuf field <code>repeated .cerbos.policy.v1.RoleDef definitions = 2 [json_name = "definitions", (.buf.validate.field) = {</code>
     * @param array<\Cerbos\Policy\V1\RoleDef>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setDefinitions($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Cerbos\Policy\V1\RoleDef::class);
        $this->definitions = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.cerbos.policy.v1.Variables variables = 3 [json_name = "variables"];</code>
     * @return \Cerbos\Policy\V1\Variables|null
     */
    public function getVariables()
    {
        return $this->variables;
    }

    public function hasVariables()
    {
        return isset($this->variables);
    }

    public function clearVariables()
    {
        unset($this->variables);
    }

    /**
     * Generated from protobuf field <code>.cerbos.policy.v1.Variables variables = 3 [json_name = "variables"];</code>
     * @param \Cerbos\Policy\V1\Variables $var
     * @return $this
     */
    public function setVariables($var)
    {
        GPBUtil::checkMessage($var, \Cerbos\Policy\V1\Variables::class);
        $this->variables = $var;

        return $this;
    }

}

