<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cerbos/policy/v1/policy.proto

namespace Cerbos\Policy\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>cerbos.policy.v1.Policy</code>
 */
class Policy extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string api_version = 1 [json_name = "apiVersion"];</code>
     */
    protected $api_version = '';
    /**
     * Generated from protobuf field <code>bool disabled = 2 [json_name = "disabled"];</code>
     */
    protected $disabled = false;
    /**
     * Generated from protobuf field <code>string description = 3 [json_name = "description"];</code>
     */
    protected $description = '';
    /**
     * Generated from protobuf field <code>.cerbos.policy.v1.Metadata metadata = 4 [json_name = "metadata"];</code>
     */
    protected $metadata = null;
    /**
     * Generated from protobuf field <code>map<string, string> variables = 8 [json_name = "variables", deprecated = true];</code>
     * @deprecated
     */
    private $variables;
    /**
     * Generated from protobuf field <code>string json_schema = 9 [json_name = "$schema"];</code>
     */
    protected $json_schema = '';
    protected $policy_type;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $api_version
     *     @type bool $disabled
     *     @type string $description
     *     @type \Cerbos\Policy\V1\Metadata $metadata
     *     @type \Cerbos\Policy\V1\ResourcePolicy $resource_policy
     *     @type \Cerbos\Policy\V1\PrincipalPolicy $principal_policy
     *     @type \Cerbos\Policy\V1\DerivedRoles $derived_roles
     *     @type \Cerbos\Policy\V1\ExportVariables $export_variables
     *     @type \Cerbos\Policy\V1\RolePolicy $role_policy
     *     @type \Cerbos\Policy\V1\ExportConstants $export_constants
     *     @type array|\Google\Protobuf\Internal\MapField $variables
     *     @type string $json_schema
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Cerbos\Policy\V1\Policy::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string api_version = 1 [json_name = "apiVersion"];</code>
     * @return string
     */
    public function getApiVersion()
    {
        return $this->api_version;
    }

    /**
     * Generated from protobuf field <code>string api_version = 1 [json_name = "apiVersion"];</code>
     * @param string $var
     * @return $this
     */
    public function setApiVersion($var)
    {
        GPBUtil::checkString($var, True);
        $this->api_version = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool disabled = 2 [json_name = "disabled"];</code>
     * @return bool
     */
    public function getDisabled()
    {
        return $this->disabled;
    }

    /**
     * Generated from protobuf field <code>bool disabled = 2 [json_name = "disabled"];</code>
     * @param bool $var
     * @return $this
     */
    public function setDisabled($var)
    {
        GPBUtil::checkBool($var);
        $this->disabled = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string description = 3 [json_name = "description"];</code>
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Generated from protobuf field <code>string description = 3 [json_name = "description"];</code>
     * @param string $var
     * @return $this
     */
    public function setDescription($var)
    {
        GPBUtil::checkString($var, True);
        $this->description = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.cerbos.policy.v1.Metadata metadata = 4 [json_name = "metadata"];</code>
     * @return \Cerbos\Policy\V1\Metadata|null
     */
    public function getMetadata()
    {
        return $this->metadata;
    }

    public function hasMetadata()
    {
        return isset($this->metadata);
    }

    public function clearMetadata()
    {
        unset($this->metadata);
    }

    /**
     * Generated from protobuf field <code>.cerbos.policy.v1.Metadata metadata = 4 [json_name = "metadata"];</code>
     * @param \Cerbos\Policy\V1\Metadata $var
     * @return $this
     */
    public function setMetadata($var)
    {
        GPBUtil::checkMessage($var, \Cerbos\Policy\V1\Metadata::class);
        $this->metadata = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.cerbos.policy.v1.ResourcePolicy resource_policy = 5 [json_name = "resourcePolicy"];</code>
     * @return \Cerbos\Policy\V1\ResourcePolicy|null
     */
    public function getResourcePolicy()
    {
        return $this->readOneof(5);
    }

    public function hasResourcePolicy()
    {
        return $this->hasOneof(5);
    }

    /**
     * Generated from protobuf field <code>.cerbos.policy.v1.ResourcePolicy resource_policy = 5 [json_name = "resourcePolicy"];</code>
     * @param \Cerbos\Policy\V1\ResourcePolicy $var
     * @return $this
     */
    public function setResourcePolicy($var)
    {
        GPBUtil::checkMessage($var, \Cerbos\Policy\V1\ResourcePolicy::class);
        $this->writeOneof(5, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.cerbos.policy.v1.PrincipalPolicy principal_policy = 6 [json_name = "principalPolicy"];</code>
     * @return \Cerbos\Policy\V1\PrincipalPolicy|null
     */
    public function getPrincipalPolicy()
    {
        return $this->readOneof(6);
    }

    public function hasPrincipalPolicy()
    {
        return $this->hasOneof(6);
    }

    /**
     * Generated from protobuf field <code>.cerbos.policy.v1.PrincipalPolicy principal_policy = 6 [json_name = "principalPolicy"];</code>
     * @param \Cerbos\Policy\V1\PrincipalPolicy $var
     * @return $this
     */
    public function setPrincipalPolicy($var)
    {
        GPBUtil::checkMessage($var, \Cerbos\Policy\V1\PrincipalPolicy::class);
        $this->writeOneof(6, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.cerbos.policy.v1.DerivedRoles derived_roles = 7 [json_name = "derivedRoles"];</code>
     * @return \Cerbos\Policy\V1\DerivedRoles|null
     */
    public function getDerivedRoles()
    {
        return $this->readOneof(7);
    }

    public function hasDerivedRoles()
    {
        return $this->hasOneof(7);
    }

    /**
     * Generated from protobuf field <code>.cerbos.policy.v1.DerivedRoles derived_roles = 7 [json_name = "derivedRoles"];</code>
     * @param \Cerbos\Policy\V1\DerivedRoles $var
     * @return $this
     */
    public function setDerivedRoles($var)
    {
        GPBUtil::checkMessage($var, \Cerbos\Policy\V1\DerivedRoles::class);
        $this->writeOneof(7, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.cerbos.policy.v1.ExportVariables export_variables = 10 [json_name = "exportVariables"];</code>
     * @return \Cerbos\Policy\V1\ExportVariables|null
     */
    public function getExportVariables()
    {
        return $this->readOneof(10);
    }

    public function hasExportVariables()
    {
        return $this->hasOneof(10);
    }

    /**
     * Generated from protobuf field <code>.cerbos.policy.v1.ExportVariables export_variables = 10 [json_name = "exportVariables"];</code>
     * @param \Cerbos\Policy\V1\ExportVariables $var
     * @return $this
     */
    public function setExportVariables($var)
    {
        GPBUtil::checkMessage($var, \Cerbos\Policy\V1\ExportVariables::class);
        $this->writeOneof(10, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.cerbos.policy.v1.RolePolicy role_policy = 11 [json_name = "rolePolicy"];</code>
     * @return \Cerbos\Policy\V1\RolePolicy|null
     */
    public function getRolePolicy()
    {
        return $this->readOneof(11);
    }

    public function hasRolePolicy()
    {
        return $this->hasOneof(11);
    }

    /**
     * Generated from protobuf field <code>.cerbos.policy.v1.RolePolicy role_policy = 11 [json_name = "rolePolicy"];</code>
     * @param \Cerbos\Policy\V1\RolePolicy $var
     * @return $this
     */
    public function setRolePolicy($var)
    {
        GPBUtil::checkMessage($var, \Cerbos\Policy\V1\RolePolicy::class);
        $this->writeOneof(11, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.cerbos.policy.v1.ExportConstants export_constants = 12 [json_name = "exportConstants"];</code>
     * @return \Cerbos\Policy\V1\ExportConstants|null
     */
    public function getExportConstants()
    {
        return $this->readOneof(12);
    }

    public function hasExportConstants()
    {
        return $this->hasOneof(12);
    }

    /**
     * Generated from protobuf field <code>.cerbos.policy.v1.ExportConstants export_constants = 12 [json_name = "exportConstants"];</code>
     * @param \Cerbos\Policy\V1\ExportConstants $var
     * @return $this
     */
    public function setExportConstants($var)
    {
        GPBUtil::checkMessage($var, \Cerbos\Policy\V1\ExportConstants::class);
        $this->writeOneof(12, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>map<string, string> variables = 8 [json_name = "variables", deprecated = true];</code>
     * @return \Google\Protobuf\Internal\MapField
     * @deprecated
     */
    public function getVariables()
    {
        if ($this->variables->count() !== 0) {
            @trigger_error('variables is deprecated.', E_USER_DEPRECATED);
        }
        return $this->variables;
    }

    /**
     * Generated from protobuf field <code>map<string, string> variables = 8 [json_name = "variables", deprecated = true];</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     * @deprecated
     */
    public function setVariables($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::STRING);
        if ($arr->count() !== 0) {
            @trigger_error('variables is deprecated.', E_USER_DEPRECATED);
        }
        $this->variables = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string json_schema = 9 [json_name = "$schema"];</code>
     * @return string
     */
    public function getJsonSchema()
    {
        return $this->json_schema;
    }

    /**
     * Generated from protobuf field <code>string json_schema = 9 [json_name = "$schema"];</code>
     * @param string $var
     * @return $this
     */
    public function setJsonSchema($var)
    {
        GPBUtil::checkString($var, True);
        $this->json_schema = $var;

        return $this;
    }

    /**
     * @return string
     */
    public function getPolicyType()
    {
        return $this->whichOneof("policy_type");
    }

}

