<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cerbos/policy/v1/policy.proto

namespace Cerbos\Policy\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>cerbos.policy.v1.PrincipalRule</code>
 */
class PrincipalRule extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string resource = 1 [json_name = "resource"];</code>
     */
    protected $resource = '';
    /**
     * Generated from protobuf field <code>repeated .cerbos.policy.v1.PrincipalRule.Action actions = 2 [json_name = "actions"];</code>
     */
    private $actions;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $resource
     *     @type \Cerbos\Policy\V1\PrincipalRule\Action[] $actions
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Cerbos\Policy\V1\Policy::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string resource = 1 [json_name = "resource"];</code>
     * @return string
     */
    public function getResource()
    {
        return $this->resource;
    }

    /**
     * Generated from protobuf field <code>string resource = 1 [json_name = "resource"];</code>
     * @param string $var
     * @return $this
     */
    public function setResource($var)
    {
        GPBUtil::checkString($var, True);
        $this->resource = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .cerbos.policy.v1.PrincipalRule.Action actions = 2 [json_name = "actions"];</code>
     * @return RepeatedField<\Cerbos\Policy\V1\PrincipalRule\Action>
     */
    public function getActions()
    {
        return $this->actions;
    }

    /**
     * Generated from protobuf field <code>repeated .cerbos.policy.v1.PrincipalRule.Action actions = 2 [json_name = "actions"];</code>
     * @param \Cerbos\Policy\V1\PrincipalRule\Action[] $var
     * @return $this
     */
    public function setActions($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Cerbos\Policy\V1\PrincipalRule\Action::class);
        $this->actions = $arr;

        return $this;
    }

}

