<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cerbos/policy/v1/policy.proto

namespace Cerbos\Policy\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>cerbos.policy.v1.RolePolicy</code>
 */
class RolePolicy extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string scope = 2 [json_name = "scope", (.buf.validate.field) = {</code>
     */
    protected $scope = '';
    /**
     * Generated from protobuf field <code>repeated .cerbos.policy.v1.RoleRule rules = 3 [json_name = "rules"];</code>
     */
    private $rules;
    protected $policy_type;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $role
     *     @type string $scope
     *     @type array<\Cerbos\Policy\V1\RoleRule>|\Google\Protobuf\Internal\RepeatedField $rules
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Cerbos\Policy\V1\Policy::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string role = 1 [json_name = "role", (.buf.validate.field) = {</code>
     * @return string
     */
    public function getRole()
    {
        return $this->readOneof(1);
    }

    public function hasRole()
    {
        return $this->hasOneof(1);
    }

    /**
     * Generated from protobuf field <code>string role = 1 [json_name = "role", (.buf.validate.field) = {</code>
     * @param string $var
     * @return $this
     */
    public function setRole($var)
    {
        GPBUtil::checkString($var, True);
        $this->writeOneof(1, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>string scope = 2 [json_name = "scope", (.buf.validate.field) = {</code>
     * @return string
     */
    public function getScope()
    {
        return $this->scope;
    }

    /**
     * Generated from protobuf field <code>string scope = 2 [json_name = "scope", (.buf.validate.field) = {</code>
     * @param string $var
     * @return $this
     */
    public function setScope($var)
    {
        GPBUtil::checkString($var, True);
        $this->scope = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .cerbos.policy.v1.RoleRule rules = 3 [json_name = "rules"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getRules()
    {
        return $this->rules;
    }

    /**
     * Generated from protobuf field <code>repeated .cerbos.policy.v1.RoleRule rules = 3 [json_name = "rules"];</code>
     * @param array<\Cerbos\Policy\V1\RoleRule>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setRules($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Cerbos\Policy\V1\RoleRule::class);
        $this->rules = $arr;

        return $this;
    }

    /**
     * @return string
     */
    public function getPolicyType()
    {
        return $this->whichOneof("policy_type");
    }

}

