<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cerbos/policy/v1/policy.proto

namespace Cerbos\Policy\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>cerbos.policy.v1.Test</code>
 */
class Test extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.cerbos.policy.v1.Test.TestName name = 1 [json_name = "name", (.buf.validate.field) = {</code>
     */
    protected $name = null;
    /**
     * Generated from protobuf field <code>string description = 2 [json_name = "description"];</code>
     */
    protected $description = '';
    /**
     * Generated from protobuf field <code>bool skip = 3 [json_name = "skip"];</code>
     */
    protected $skip = false;
    /**
     * Generated from protobuf field <code>string skip_reason = 4 [json_name = "skipReason"];</code>
     */
    protected $skip_reason = '';
    /**
     * Generated from protobuf field <code>.cerbos.engine.v1.CheckInput input = 5 [json_name = "input", (.buf.validate.field) = {</code>
     */
    protected $input = null;
    /**
     * Generated from protobuf field <code>map<string, .cerbos.effect.v1.Effect> expected = 6 [json_name = "expected", (.buf.validate.field) = {</code>
     */
    private $expected;
    /**
     * Generated from protobuf field <code>.cerbos.policy.v1.TestOptions options = 7 [json_name = "options"];</code>
     */
    protected $options = null;
    /**
     * Generated from protobuf field <code>map<string, .cerbos.policy.v1.Test.OutputEntries> expected_outputs = 8 [json_name = "expectedOutputs"];</code>
     */
    private $expected_outputs;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Cerbos\Policy\V1\Test\TestName $name
     *     @type string $description
     *     @type bool $skip
     *     @type string $skip_reason
     *     @type \Cerbos\Engine\V1\CheckInput $input
     *     @type array|\Google\Protobuf\Internal\MapField $expected
     *     @type \Cerbos\Policy\V1\TestOptions $options
     *     @type array|\Google\Protobuf\Internal\MapField $expected_outputs
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Cerbos\Policy\V1\Policy::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.cerbos.policy.v1.Test.TestName name = 1 [json_name = "name", (.buf.validate.field) = {</code>
     * @return \Cerbos\Policy\V1\Test\TestName|null
     */
    public function getName()
    {
        return $this->name;
    }

    public function hasName()
    {
        return isset($this->name);
    }

    public function clearName()
    {
        unset($this->name);
    }

    /**
     * Generated from protobuf field <code>.cerbos.policy.v1.Test.TestName name = 1 [json_name = "name", (.buf.validate.field) = {</code>
     * @param \Cerbos\Policy\V1\Test\TestName $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkMessage($var, \Cerbos\Policy\V1\Test\TestName::class);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string description = 2 [json_name = "description"];</code>
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Generated from protobuf field <code>string description = 2 [json_name = "description"];</code>
     * @param string $var
     * @return $this
     */
    public function setDescription($var)
    {
        GPBUtil::checkString($var, True);
        $this->description = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool skip = 3 [json_name = "skip"];</code>
     * @return bool
     */
    public function getSkip()
    {
        return $this->skip;
    }

    /**
     * Generated from protobuf field <code>bool skip = 3 [json_name = "skip"];</code>
     * @param bool $var
     * @return $this
     */
    public function setSkip($var)
    {
        GPBUtil::checkBool($var);
        $this->skip = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string skip_reason = 4 [json_name = "skipReason"];</code>
     * @return string
     */
    public function getSkipReason()
    {
        return $this->skip_reason;
    }

    /**
     * Generated from protobuf field <code>string skip_reason = 4 [json_name = "skipReason"];</code>
     * @param string $var
     * @return $this
     */
    public function setSkipReason($var)
    {
        GPBUtil::checkString($var, True);
        $this->skip_reason = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.cerbos.engine.v1.CheckInput input = 5 [json_name = "input", (.buf.validate.field) = {</code>
     * @return \Cerbos\Engine\V1\CheckInput|null
     */
    public function getInput()
    {
        return $this->input;
    }

    public function hasInput()
    {
        return isset($this->input);
    }

    public function clearInput()
    {
        unset($this->input);
    }

    /**
     * Generated from protobuf field <code>.cerbos.engine.v1.CheckInput input = 5 [json_name = "input", (.buf.validate.field) = {</code>
     * @param \Cerbos\Engine\V1\CheckInput $var
     * @return $this
     */
    public function setInput($var)
    {
        GPBUtil::checkMessage($var, \Cerbos\Engine\V1\CheckInput::class);
        $this->input = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>map<string, .cerbos.effect.v1.Effect> expected = 6 [json_name = "expected", (.buf.validate.field) = {</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getExpected()
    {
        return $this->expected;
    }

    /**
     * Generated from protobuf field <code>map<string, .cerbos.effect.v1.Effect> expected = 6 [json_name = "expected", (.buf.validate.field) = {</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setExpected($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::ENUM, \Cerbos\Effect\V1\Effect::class);
        $this->expected = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.cerbos.policy.v1.TestOptions options = 7 [json_name = "options"];</code>
     * @return \Cerbos\Policy\V1\TestOptions|null
     */
    public function getOptions()
    {
        return $this->options;
    }

    public function hasOptions()
    {
        return isset($this->options);
    }

    public function clearOptions()
    {
        unset($this->options);
    }

    /**
     * Generated from protobuf field <code>.cerbos.policy.v1.TestOptions options = 7 [json_name = "options"];</code>
     * @param \Cerbos\Policy\V1\TestOptions $var
     * @return $this
     */
    public function setOptions($var)
    {
        GPBUtil::checkMessage($var, \Cerbos\Policy\V1\TestOptions::class);
        $this->options = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>map<string, .cerbos.policy.v1.Test.OutputEntries> expected_outputs = 8 [json_name = "expectedOutputs"];</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getExpectedOutputs()
    {
        return $this->expected_outputs;
    }

    /**
     * Generated from protobuf field <code>map<string, .cerbos.policy.v1.Test.OutputEntries> expected_outputs = 8 [json_name = "expectedOutputs"];</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setExpectedOutputs($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::MESSAGE, \Cerbos\Policy\V1\Test\OutputEntries::class);
        $this->expected_outputs = $arr;

        return $this;
    }

}

