<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: google/api/expr/v1alpha1/syntax.proto

namespace Google\Api\Expr\V1alpha1\SourceInfo;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * An extension that was requested for the source expression.
 *
 * Generated from protobuf message <code>google.api.expr.v1alpha1.SourceInfo.Extension</code>
 */
class Extension extends \Google\Protobuf\Internal\Message
{
    /**
     * Identifier for the extension. Example: constant_folding
     *
     * Generated from protobuf field <code>string id = 1 [json_name = "id"];</code>
     */
    protected $id = '';
    /**
     * If set, the listed components must understand the extension for the
     * expression to evaluate correctly.
     * This field has set semantics, repeated values should be deduplicated.
     *
     * Generated from protobuf field <code>repeated .google.api.expr.v1alpha1.SourceInfo.Extension.Component affected_components = 2 [json_name = "affectedComponents"];</code>
     */
    private $affected_components;
    /**
     * Version info. May be skipped if it isn't meaningful for the extension.
     * (for example constant_folding might always be v0.0).
     *
     * Generated from protobuf field <code>.google.api.expr.v1alpha1.SourceInfo.Extension.Version version = 3 [json_name = "version"];</code>
     */
    protected $version = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $id
     *           Identifier for the extension. Example: constant_folding
     *     @type array<int>|\Google\Protobuf\Internal\RepeatedField $affected_components
     *           If set, the listed components must understand the extension for the
     *           expression to evaluate correctly.
     *           This field has set semantics, repeated values should be deduplicated.
     *     @type \Google\Api\Expr\V1alpha1\SourceInfo\Extension\Version $version
     *           Version info. May be skipped if it isn't meaningful for the extension.
     *           (for example constant_folding might always be v0.0).
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Google\Api\Expr\V1Alpha1\Syntax::initOnce();
        parent::__construct($data);
    }

    /**
     * Identifier for the extension. Example: constant_folding
     *
     * Generated from protobuf field <code>string id = 1 [json_name = "id"];</code>
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Identifier for the extension. Example: constant_folding
     *
     * Generated from protobuf field <code>string id = 1 [json_name = "id"];</code>
     * @param string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, True);
        $this->id = $var;

        return $this;
    }

    /**
     * If set, the listed components must understand the extension for the
     * expression to evaluate correctly.
     * This field has set semantics, repeated values should be deduplicated.
     *
     * Generated from protobuf field <code>repeated .google.api.expr.v1alpha1.SourceInfo.Extension.Component affected_components = 2 [json_name = "affectedComponents"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getAffectedComponents()
    {
        return $this->affected_components;
    }

    /**
     * If set, the listed components must understand the extension for the
     * expression to evaluate correctly.
     * This field has set semantics, repeated values should be deduplicated.
     *
     * Generated from protobuf field <code>repeated .google.api.expr.v1alpha1.SourceInfo.Extension.Component affected_components = 2 [json_name = "affectedComponents"];</code>
     * @param array<int>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setAffectedComponents($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::ENUM, \Google\Api\Expr\V1alpha1\SourceInfo\Extension\Component::class);
        $this->affected_components = $arr;

        return $this;
    }

    /**
     * Version info. May be skipped if it isn't meaningful for the extension.
     * (for example constant_folding might always be v0.0).
     *
     * Generated from protobuf field <code>.google.api.expr.v1alpha1.SourceInfo.Extension.Version version = 3 [json_name = "version"];</code>
     * @return \Google\Api\Expr\V1alpha1\SourceInfo\Extension\Version|null
     */
    public function getVersion()
    {
        return $this->version;
    }

    public function hasVersion()
    {
        return isset($this->version);
    }

    public function clearVersion()
    {
        unset($this->version);
    }

    /**
     * Version info. May be skipped if it isn't meaningful for the extension.
     * (for example constant_folding might always be v0.0).
     *
     * Generated from protobuf field <code>.google.api.expr.v1alpha1.SourceInfo.Extension.Version version = 3 [json_name = "version"];</code>
     * @param \Google\Api\Expr\V1alpha1\SourceInfo\Extension\Version $var
     * @return $this
     */
    public function setVersion($var)
    {
        GPBUtil::checkMessage($var, \Google\Api\Expr\V1alpha1\SourceInfo\Extension\Version::class);
        $this->version = $var;

        return $this;
    }

}

