<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cerbos/cloud/apikey/v1/apikey.proto

namespace Cerbos\Cloud\Apikey\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>cerbos.cloud.apikey.v1.RegisterDeviceResponse</code>
 */
class RegisterDeviceResponse extends \Google\Protobuf\Internal\Message
{
    protected $message;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $verification_url
     *     @type \Cerbos\Cloud\Auth\V1\DeviceToken $device_token
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Cerbos\Cloud\Apikey\V1\Apikey::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string verification_url = 1 [json_name = "verificationUrl"];</code>
     * @return string
     */
    public function getVerificationUrl()
    {
        return $this->readOneof(1);
    }

    public function hasVerificationUrl()
    {
        return $this->hasOneof(1);
    }

    /**
     * Generated from protobuf field <code>string verification_url = 1 [json_name = "verificationUrl"];</code>
     * @param string $var
     * @return $this
     */
    public function setVerificationUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->writeOneof(1, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.cerbos.cloud.auth.v1.DeviceToken device_token = 2 [json_name = "deviceToken"];</code>
     * @return \Cerbos\Cloud\Auth\V1\DeviceToken|null
     */
    public function getDeviceToken()
    {
        return $this->readOneof(2);
    }

    public function hasDeviceToken()
    {
        return $this->hasOneof(2);
    }

    /**
     * Generated from protobuf field <code>.cerbos.cloud.auth.v1.DeviceToken device_token = 2 [json_name = "deviceToken"];</code>
     * @param \Cerbos\Cloud\Auth\V1\DeviceToken $var
     * @return $this
     */
    public function setDeviceToken($var)
    {
        GPBUtil::checkMessage($var, \Cerbos\Cloud\Auth\V1\DeviceToken::class);
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getMessage()
    {
        return $this->whichOneof("message");
    }

}

