<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cerbos/response/v1/response.proto

namespace Cerbos\Response\V1\PlaygroundTestResponse;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>cerbos.response.v1.PlaygroundTestResponse.TestResults</code>
 */
class TestResults extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.cerbos.policy.v1.TestResults results = 1 [json_name = "results"];</code>
     */
    protected $results = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Cerbos\Policy\V1\TestResults $results
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Cerbos\Response\V1\Response::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.cerbos.policy.v1.TestResults results = 1 [json_name = "results"];</code>
     * @return \Cerbos\Policy\V1\TestResults|null
     */
    public function getResults()
    {
        return $this->results;
    }

    public function hasResults()
    {
        return isset($this->results);
    }

    public function clearResults()
    {
        unset($this->results);
    }

    /**
     * Generated from protobuf field <code>.cerbos.policy.v1.TestResults results = 1 [json_name = "results"];</code>
     * @param \Cerbos\Policy\V1\TestResults $var
     * @return $this
     */
    public function setResults($var)
    {
        GPBUtil::checkMessage($var, \Cerbos\Policy\V1\TestResults::class);
        $this->results = $var;

        return $this;
    }

}

