<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: authzen/authorization/v1/evaluation.proto

namespace Authzen\Authorization\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * AuthZEN evaluations request message
 *
 * Generated from protobuf message <code>authzen.authorization.v1.AccessEvaluationBatchRequest</code>
 */
class AccessEvaluationBatchRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.authzen.authorization.v1.Subject subject = 1 [json_name = "subject"];</code>
     */
    protected $subject = null;
    /**
     * Generated from protobuf field <code>.authzen.authorization.v1.Resource resource = 2 [json_name = "resource"];</code>
     */
    protected $resource = null;
    /**
     * Generated from protobuf field <code>.authzen.authorization.v1.Action action = 3 [json_name = "action"];</code>
     */
    protected $action = null;
    /**
     * Generated from protobuf field <code>map<string, .google.protobuf.Value> context = 4 [json_name = "context", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     */
    private $context;
    /**
     * Generated from protobuf field <code>repeated .authzen.authorization.v1.AccessEvaluationBatchRequest.Evaluation evaluations = 5 [json_name = "evaluations"];</code>
     */
    private $evaluations;
    /**
     * Generated from protobuf field <code>.authzen.authorization.v1.AccessEvaluationsOptions options = 6 [json_name = "options"];</code>
     */
    protected $options = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Authzen\Authorization\V1\Subject $subject
     *     @type \Authzen\Authorization\V1\Resource $resource
     *     @type \Authzen\Authorization\V1\Action $action
     *     @type array|\Google\Protobuf\Internal\MapField $context
     *     @type \Authzen\Authorization\V1\AccessEvaluationBatchRequest\Evaluation[] $evaluations
     *     @type \Authzen\Authorization\V1\AccessEvaluationsOptions $options
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Authzen\Authorization\V1\Evaluation::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.authzen.authorization.v1.Subject subject = 1 [json_name = "subject"];</code>
     * @return \Authzen\Authorization\V1\Subject|null
     */
    public function getSubject()
    {
        return $this->subject;
    }

    public function hasSubject()
    {
        return isset($this->subject);
    }

    public function clearSubject()
    {
        unset($this->subject);
    }

    /**
     * Generated from protobuf field <code>.authzen.authorization.v1.Subject subject = 1 [json_name = "subject"];</code>
     * @param \Authzen\Authorization\V1\Subject $var
     * @return $this
     */
    public function setSubject($var)
    {
        GPBUtil::checkMessage($var, \Authzen\Authorization\V1\Subject::class);
        $this->subject = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.authzen.authorization.v1.Resource resource = 2 [json_name = "resource"];</code>
     * @return \Authzen\Authorization\V1\Resource|null
     */
    public function getResource()
    {
        return $this->resource;
    }

    public function hasResource()
    {
        return isset($this->resource);
    }

    public function clearResource()
    {
        unset($this->resource);
    }

    /**
     * Generated from protobuf field <code>.authzen.authorization.v1.Resource resource = 2 [json_name = "resource"];</code>
     * @param \Authzen\Authorization\V1\Resource $var
     * @return $this
     */
    public function setResource($var)
    {
        GPBUtil::checkMessage($var, \Authzen\Authorization\V1\Resource::class);
        $this->resource = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.authzen.authorization.v1.Action action = 3 [json_name = "action"];</code>
     * @return \Authzen\Authorization\V1\Action|null
     */
    public function getAction()
    {
        return $this->action;
    }

    public function hasAction()
    {
        return isset($this->action);
    }

    public function clearAction()
    {
        unset($this->action);
    }

    /**
     * Generated from protobuf field <code>.authzen.authorization.v1.Action action = 3 [json_name = "action"];</code>
     * @param \Authzen\Authorization\V1\Action $var
     * @return $this
     */
    public function setAction($var)
    {
        GPBUtil::checkMessage($var, \Authzen\Authorization\V1\Action::class);
        $this->action = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>map<string, .google.protobuf.Value> context = 4 [json_name = "context", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getContext()
    {
        return $this->context;
    }

    /**
     * Generated from protobuf field <code>map<string, .google.protobuf.Value> context = 4 [json_name = "context", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setContext($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::MESSAGE, \Google\Protobuf\Value::class);
        $this->context = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .authzen.authorization.v1.AccessEvaluationBatchRequest.Evaluation evaluations = 5 [json_name = "evaluations"];</code>
     * @return RepeatedField<\Authzen\Authorization\V1\AccessEvaluationBatchRequest\Evaluation>
     */
    public function getEvaluations()
    {
        return $this->evaluations;
    }

    /**
     * Generated from protobuf field <code>repeated .authzen.authorization.v1.AccessEvaluationBatchRequest.Evaluation evaluations = 5 [json_name = "evaluations"];</code>
     * @param \Authzen\Authorization\V1\AccessEvaluationBatchRequest\Evaluation[] $var
     * @return $this
     */
    public function setEvaluations($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Authzen\Authorization\V1\AccessEvaluationBatchRequest\Evaluation::class);
        $this->evaluations = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.authzen.authorization.v1.AccessEvaluationsOptions options = 6 [json_name = "options"];</code>
     * @return \Authzen\Authorization\V1\AccessEvaluationsOptions|null
     */
    public function getOptions()
    {
        return $this->options;
    }

    public function hasOptions()
    {
        return isset($this->options);
    }

    public function clearOptions()
    {
        unset($this->options);
    }

    /**
     * Generated from protobuf field <code>.authzen.authorization.v1.AccessEvaluationsOptions options = 6 [json_name = "options"];</code>
     * @param \Authzen\Authorization\V1\AccessEvaluationsOptions $var
     * @return $this
     */
    public function setOptions($var)
    {
        GPBUtil::checkMessage($var, \Authzen\Authorization\V1\AccessEvaluationsOptions::class);
        $this->options = $var;

        return $this;
    }

}

