<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: authzen/authorization/v1/evaluation.proto

namespace Authzen\Authorization\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * AccessEvaluationsOptions captures optional execution controls for batch requests.
 *
 * Generated from protobuf message <code>authzen.authorization.v1.AccessEvaluationsOptions</code>
 */
class AccessEvaluationsOptions extends \Google\Protobuf\Internal\Message
{
    /**
     * Controls how the PDP should execute the evaluations array.
     *
     * Generated from protobuf field <code>string evaluations_semantic = 1 [json_name = "evaluationsSemantic", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     */
    protected $evaluations_semantic = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $evaluations_semantic
     *           Controls how the PDP should execute the evaluations array.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Authzen\Authorization\V1\Evaluation::initOnce();
        parent::__construct($data);
    }

    /**
     * Controls how the PDP should execute the evaluations array.
     *
     * Generated from protobuf field <code>string evaluations_semantic = 1 [json_name = "evaluationsSemantic", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @return string
     */
    public function getEvaluationsSemantic()
    {
        return $this->evaluations_semantic;
    }

    /**
     * Controls how the PDP should execute the evaluations array.
     *
     * Generated from protobuf field <code>string evaluations_semantic = 1 [json_name = "evaluationsSemantic", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @param string $var
     * @return $this
     */
    public function setEvaluationsSemantic($var)
    {
        GPBUtil::checkString($var, True);
        $this->evaluations_semantic = $var;

        return $this;
    }

}

