<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: authzen/authorization/v1/evaluation.proto

namespace Authzen\Authorization\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * AuthZEN evaluation response message
 *
 * Generated from protobuf message <code>authzen.authorization.v1.AccessEvaluationResponse</code>
 */
class AccessEvaluationResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>optional bool decision = 1 [json_name = "decision", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     */
    protected $decision = null;
    /**
     * Generated from protobuf field <code>map<string, .google.protobuf.Value> context = 2 [json_name = "context", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     */
    private $context;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $decision
     *     @type array|\Google\Protobuf\Internal\MapField $context
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Authzen\Authorization\V1\Evaluation::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional bool decision = 1 [json_name = "decision", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @return bool
     */
    public function getDecision()
    {
        return isset($this->decision) ? $this->decision : false;
    }

    public function hasDecision()
    {
        return isset($this->decision);
    }

    public function clearDecision()
    {
        unset($this->decision);
    }

    /**
     * Generated from protobuf field <code>optional bool decision = 1 [json_name = "decision", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @param bool $var
     * @return $this
     */
    public function setDecision($var)
    {
        GPBUtil::checkBool($var);
        $this->decision = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>map<string, .google.protobuf.Value> context = 2 [json_name = "context", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getContext()
    {
        return $this->context;
    }

    /**
     * Generated from protobuf field <code>map<string, .google.protobuf.Value> context = 2 [json_name = "context", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setContext($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::MESSAGE, \Google\Protobuf\Value::class);
        $this->context = $arr;

        return $this;
    }

}

