<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cerbos/response/v1/response.proto

namespace Cerbos\Response\V1\CheckResourceSetResponse\Meta;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>cerbos.response.v1.CheckResourceSetResponse.Meta.ActionMeta</code>
 */
class ActionMeta extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>map<string, .cerbos.response.v1.CheckResourceSetResponse.Meta.EffectMeta> actions = 1 [json_name = "actions", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     */
    private $actions;
    /**
     * Generated from protobuf field <code>repeated string effective_derived_roles = 2 [json_name = "effectiveDerivedRoles", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     */
    private $effective_derived_roles;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array|\Google\Protobuf\Internal\MapField $actions
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $effective_derived_roles
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Cerbos\Response\V1\Response::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>map<string, .cerbos.response.v1.CheckResourceSetResponse.Meta.EffectMeta> actions = 1 [json_name = "actions", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getActions()
    {
        return $this->actions;
    }

    /**
     * Generated from protobuf field <code>map<string, .cerbos.response.v1.CheckResourceSetResponse.Meta.EffectMeta> actions = 1 [json_name = "actions", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setActions($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::MESSAGE, \Cerbos\Response\V1\CheckResourceSetResponse\Meta\EffectMeta::class);
        $this->actions = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string effective_derived_roles = 2 [json_name = "effectiveDerivedRoles", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getEffectiveDerivedRoles()
    {
        return $this->effective_derived_roles;
    }

    /**
     * Generated from protobuf field <code>repeated string effective_derived_roles = 2 [json_name = "effectiveDerivedRoles", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setEffectiveDerivedRoles($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->effective_derived_roles = $arr;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(ActionMeta::class, \Cerbos\Response\V1\CheckResourceSetResponse_Meta_ActionMeta::class);

