<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cerbos/response/v1/response.proto

namespace Cerbos\Response\V1\CheckResourceSetResponse\Meta;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>cerbos.response.v1.CheckResourceSetResponse.Meta.EffectMeta</code>
 */
class EffectMeta extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string matched_policy = 1 [json_name = "matchedPolicy", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     */
    protected $matched_policy = '';
    /**
     * Generated from protobuf field <code>string matched_scope = 2 [json_name = "matchedScope", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     */
    protected $matched_scope = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $matched_policy
     *     @type string $matched_scope
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Cerbos\Response\V1\Response::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string matched_policy = 1 [json_name = "matchedPolicy", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @return string
     */
    public function getMatchedPolicy()
    {
        return $this->matched_policy;
    }

    /**
     * Generated from protobuf field <code>string matched_policy = 1 [json_name = "matchedPolicy", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @param string $var
     * @return $this
     */
    public function setMatchedPolicy($var)
    {
        GPBUtil::checkString($var, True);
        $this->matched_policy = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string matched_scope = 2 [json_name = "matchedScope", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @return string
     */
    public function getMatchedScope()
    {
        return $this->matched_scope;
    }

    /**
     * Generated from protobuf field <code>string matched_scope = 2 [json_name = "matchedScope", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {</code>
     * @param string $var
     * @return $this
     */
    public function setMatchedScope($var)
    {
        GPBUtil::checkString($var, True);
        $this->matched_scope = $var;

        return $this;
    }

}

