---
name: CI

on:
  pull_request:
    branches:
      - main
      - "v*"

defaults:
  run:
    shell: bash

permissions: {}

jobs:
  validate-lint-statically-analyze-and-unit-test:
    name: Run validation, linters, static analysis and unit tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-version: ["8.4"]
        experimental: [false]
    steps:
      - name: Check out repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          lfs: true
          persist-credentials: false

      - name: Set up PHP
        uses: shivammathur/setup-php@accd6127cb78bee3e8082180cb391013d204ef9f # 2.37.0
        with:
          php-version: ${{ matrix.php-version }}
          coverage: xdebug
          extensions: "grpc"

      - name: Install Buf
        uses: cerbos/actions/install-tools@bb5570805858670fd33787e9ded60b8c1140b2a1 # main
        with:
          tools: buf

      - name: Validate
        run: make validate-composer

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Generate
        env:
          BUF_TOKEN: ${{ secrets.BUF_TOKEN }}
        run: make generate

      - name: Lint
        run: make lint

      - name: Static analysis
        run: make static-analysis

      - name: Check repo status
        uses: cerbos/actions/check-repo-status@bb5570805858670fd33787e9ded60b8c1140b2a1 # main

      - name: Run cerbos service
        run: docker compose up -d

      - name: Run unit tests
        env:
          CERBOS_HUB_API_ENDPOINT: "${{ secrets.CERBOS_HUB_API_ENDPOINT }}"
          CERBOS_HUB_CLIENT_ID: "${{ secrets.CERBOS_HUB_CLIENT_ID }}"
          CERBOS_HUB_CLIENT_SECRET: "${{ secrets.CERBOS_HUB_CLIENT_SECRET }}"
          CERBOS_HUB_STORE_ID: "${{ secrets.CERBOS_HUB_STORE_ID }}"
        run: make test

      - name: Stop cerbos service
        run: docker compose down
