---
name: CI

on:
  pull_request:
    branches:
      - main
      - "v*"

defaults:
  run:
    shell: bash

permissions: {}

jobs:
  validate-lint-statically-analyze-and-unit-test:
    name: Run validation, linters, static analysis and unit tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        php-version: ["8.4", "8.5"]
        experimental: [false]
    steps:
      - name: Check out repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          lfs: true
          persist-credentials: false

      - name: Set up Buf
        uses: cerbos/actions/install-tools@d2c46d81505b3c938d9eaa51af6d5ef4020cd4bf # main
        with:
          tools: buf

      - name: Set up just
        uses: cerbos/actions/install-tools@d2c46d81505b3c938d9eaa51af6d5ef4020cd4bf # main
        with:
          tools: just

      - name: Set up PHP
        uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: xdebug
          extensions: "grpc"

      - name: Validate
        run: just validate-composer

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Generate
        env:
          BUF_TOKEN: ${{ secrets.BUF_TOKEN }}
        run: just generate

      - name: Lint
        run: just lint

      - name: Static analysis
        run: just static-analysis

      - name: Check repo status
        uses: cerbos/actions/check-repo-status@d2c46d81505b3c938d9eaa51af6d5ef4020cd4bf # main

      - name: Run unit tests
        env:
          CERBOS_HUB_API_ENDPOINT: "${{ secrets.CERBOS_HUB_API_ENDPOINT }}"
          CERBOS_HUB_CLIENT_ID: "${{ secrets.CERBOS_HUB_CLIENT_ID }}"
          CERBOS_HUB_CLIENT_SECRET: "${{ secrets.CERBOS_HUB_CLIENT_SECRET }}"
          CERBOS_HUB_STORE_ID: "${{ secrets.CERBOS_HUB_STORE_ID }}"
        run: just test
